require( 'ffi/winapi/headers/windows' )
local ffi = require( 'ffi' )
ffi.cdef [[
  typedef enum POWER_INFORMATION_LEVEL {
    SystemPowerPolicyAc = 0,
    SystemPowerPolicyDc = 1,
    VerifySystemPolicyAc = 2,
    VerifySystemPolicyDc = 3,
    SystemPowerCapabilities = 4,
    SystemBatteryState = 5,
    SystemPowerStateHandler = 6,
    ProcessorStateHandler = 7,
    SystemPowerPolicyCurrent = 8,
    AdministratorPowerPolicy = 9,
    SystemReserveHiberFile = 10,
    ProcessorInformation = 11,
    SystemPowerInformation = 12,
    ProcessorStateHandler2 = 13,
    LastWakeTime = 14,
    LastSleepTime = 15,
    SystemExecutionState = 16,
    SystemPowerStateNotifyHandler = 17,
    ProcessorPowerPolicyAc = 18,
    ProcessorPowerPolicyDc = 19,
    VerifyProcessorPowerPolicyAc = 20,
    VerifyProcessorPowerPolicyDc = 21,
    ProcessorPowerPolicyCurrent = 22,
    SystemPowerStateLogging = 23,
    SystemPowerLoggingEntry = 24,
    SetPowerSettingValue = 25,
    NotifyUserPowerSetting = 26,
    GetPowerTransitionVetoes = 27,
    SetPowerTransitionVeto = 28,
    SystemVideoState = 29,
    TraceApplicationPowerMessage = 30,
    TraceApplicationPowerMessageEnd = 31,
    ProcessorPerfStates = 32,
    ProcessorIdleStates = 33,
    ProcessorThrottleStates = 34,
    SystemWakeSource = 35,
    SystemHiberFileInformation = 36,
    TraceServicePowerMessage = 37,
    ProcessorLoad = 38,
    PowerShutdownNotification = 39,
  } POWER_INFORMATION_LEVEL;
  typedef enum POWER_DATA_ACCESSOR {
    ACCESS_AC_POWER_SETTING_INDEX = 0,
    ACCESS_DC_POWER_SETTING_INDEX = 1,
    ACCESS_FRIENDLY_NAME = 2,
    ACCESS_DESCRIPTION = 3,
    ACCESS_POSSIBLE_POWER_SETTING = 4,
    ACCESS_POSSIBLE_POWER_SETTING_FRIENDLY_NAME = 5,
    ACCESS_POSSIBLE_POWER_SETTING_DESCRIPTION = 6,
    ACCESS_DEFAULT_AC_POWER_SETTING = 7,
    ACCESS_DEFAULT_DC_POWER_SETTING = 8,
    ACCESS_POSSIBLE_VALUE_MIN = 9,
    ACCESS_POSSIBLE_VALUE_MAX = 10,
    ACCESS_POSSIBLE_VALUE_INCREMENT = 11,
    ACCESS_POSSIBLE_VALUE_UNITS = 12,
    ACCESS_ICON_RESOURCE = 13,
    ACCESS_DEFAULT_SECURITY_DESCRIPTOR = 14,
    ACCESS_ATTRIBUTES = 15,
    ACCESS_SCHEME = 16,
    ACCESS_SUBGROUP = 17,
    ACCESS_INDIVIDUAL_SETTING = 18,
    ACCESS_ACTIVE_SCHEME = 19,
    ACCESS_CREATE_SCHEME = 20,
  } POWER_DATA_ACCESSOR;
  typedef enum POWER_ACTION {
    PowerActionNone = 0,
    PowerActionReserved = 1,
    PowerActionSleep = 2,
    PowerActionHibernate = 3,
    PowerActionShutdown = 4,
    PowerActionShutdownReset = 5,
    PowerActionShutdownOff = 6,
    PowerActionWarmEject = 7,
  } POWER_ACTION;
  typedef enum SYSTEM_POWER_STATE {
    PowerSystemUnspecified = 0,
    PowerSystemWorking = 1,
    PowerSystemSleeping1 = 2,
    PowerSystemSleeping2 = 3,
    PowerSystemSleeping3 = 4,
    PowerSystemHibernate = 5,
    PowerSystemShutdown = 6,
  } SYSTEM_POWER_STATE;
]]
