local ffi = require( "ffi" )
ffi.cdef [[
  typedef enum WINAPI_CommDlgErrorCode {
    CDERR_DIALOGFAILURE: The dialog box could not be created. The common dialog box function's call to the DialogBox function failed. For example, this error occurs if the common dialog box call specifies an invalid window handle. = 0xFFFF,
    CDERR_STRUCTSIZE: The lStructSize member of the initialization structure for the corresponding common dialog box is invalid. = 0x0001,
    CDERR_INITIALIZATION: The common dialog box function failed during initialization. This error often occurs when sufficient memory is not available. = 0x0002,
    CDERR_NOTEMPLATE: The ENABLETEMPLATE flag was set in the Flags member of the initialization structure for the corresponding common dialog box, but you failed to provide a corresponding template. = 0x0003,
    CDERR_NOHINSTANCE: The ENABLETEMPLATE flag was set in the Flags member of the initialization structure for the corresponding common dialog box, but you failed to provide a corresponding instance handle. = 0x0004,
    CDERR_LOADSTRFAILURE: The common dialog box function failed to load a specified string. = 0x0005,
    CDERR_FINDRESFAILURE: The common dialog box function failed to find a specified resource. = 0x0006,
    CDERR_LOADRESFAILURE: The common dialog box function failed to load a specified resource. = 0x0007,
    CDERR_LOCKRESFAILURE: The common dialog box function failed to lock a specified resource. = 0x0008,
    CDERR_MEMALLOCFAILURE: The common dialog box function was unable to allocate memory for internal structures. = 0x0009,
    CDERR_MEMLOCKFAILURE: The common dialog box function was unable to lock the memory associated with a handle. = 0x000A,
    CDERR_NOHOOKL: The ENABLEHOOK flag was set in the Flags member of the initialization structure for the corresponding common dialog box, but you failed to provide a pointer to a corresponding hook procedure. = 0x000B,
    CDERR_REGISTERMSGFAIL: The RegisterWindowMessage function returned an error code when it was called by the common dialog box function. = 0x000C,
    PDERR_SETUPFAILURE: The PrintDlg function failed to load the required resources. = 0x1001,
    PDERR_PARSEFAILURE: The PrintDlg function failed to parse the strings in the [devices] section of the WIN.INI file. = 0x1002,
    PDERR_RETDEFFAILURE: The PD_RETURNDEFAULT flag was specified in the Flags member of the PRINTDLG structure, but the hDevMode or hDevNames member was not NULL. = 0x1003,
    PDERR_LOADDRVFAILURE: The PrintDlg function failed to load the device driver for the specified printer. = 0x1004,
    PDERR_GETDEVMODEFAIL: The printer driver failed to initialize a DEVMODE structure. = 0x1005,
    PDERR_INITFAILURE: The PrintDlg function failed during initialization, and there is no more specific extended error code to describe the failure. This is the generic default error code for the function. = 0x1006,
    PDERR_NODEVICES: No printer drivers were found. = 0x1007,
    PDERR_NODEFAULTPRN: A default printer does not exist. = 0x1008,
    PDERR_DNDMMISMATCH: The data in the DEVMODE and DEVNAMES structures describes two different printers. = 0x1009,
    PDERR_CREATEICFAILURE: The PrintDlg function failed when it attempted to create an information context. = 0x100A,
    PDERR_PRINTERNOTFOUND: The [devices] section of the WIN.INI file did not contain an entry for the requested printer. = 0x100B,
    PDERR_DEFAULTDIFFERENT: You called the PrintDlg function with the DN_DEFAULTPRN flag specified in the wDefault member of the DEVNAMES structure, but the printer described by the other structure members did not match the current default printer. = 0x100C,
    CFERR_NOFONTS: No fonts exist. = 0x2001,
    CFERR_MAXLESSTHANMIN: The size specified in the nSizeMax member of the CHOOSEFONT structure is less than the size specified in the nSizeMin member. = 0x2002,
    FNERR_SUBCLASSFAILURE: An attempt to subclass a list box failed because sufficient memory was not available. = 0x3001,
    FNERR_BUFFERTOOSMALL: The buffer pointed to by the lpstrFile member of the OPENFILENAME structure is too small for the file name specified by the user. = 0x3003,
    FNERR_INVALIDFILENAME: A file name is invalid. = 0x3002,
    FRERR_BUFFERLENGTHZERO: A member of the FINDREPLACE structure points to an invalid buffer. = 0x4001,
  } WINAPI_CommDlgErrorCode;
]]
