local ffi = require( 'ffi' )
ffi.cdef [[
  typedef DWORD WINAPI_CommDlgErrorCode; //Alias
  static const DWORD CDERR_DIALOGFAILURE = 0xFFFF;
  static const DWORD CDERR_STRUCTSIZE = 0x0001;
  static const DWORD CDERR_INITIALIZATION = 0x0002;
  static const DWORD CDERR_NOTEMPLATE = 0x0003;
  static const DWORD CDERR_NOHINSTANCE = 0x0004;
  static const DWORD CDERR_LOADSTRFAILURE = 0x0005;
  static const DWORD CDERR_FINDRESFAILURE = 0x0006;
  static const DWORD CDERR_LOADRESFAILURE = 0x0007;
  static const DWORD CDERR_LOCKRESFAILURE = 0x0008;
  static const DWORD CDERR_MEMALLOCFAILURE = 0x0009;
  static const DWORD CDERR_MEMLOCKFAILURE = 0x000A;
  static const DWORD CDERR_NOHOOKL = 0x000B;
  static const DWORD CDERR_REGISTERMSGFAIL = 0x000C;
  static const DWORD PDERR_SETUPFAILURE = 0x1001;
  static const DWORD PDERR_PARSEFAILURE = 0x1002;
  static const DWORD PDERR_RETDEFFAILURE = 0x1003;
  static const DWORD PDERR_LOADDRVFAILURE = 0x1004;
  static const DWORD PDERR_GETDEVMODEFAIL = 0x1005;
  static const DWORD PDERR_INITFAILURE = 0x1006;
  static const DWORD PDERR_NODEVICES = 0x1007;
  static const DWORD PDERR_NODEFAULTPRN = 0x1008;
  static const DWORD PDERR_DNDMMISMATCH = 0x1009;
  static const DWORD PDERR_CREATEICFAILURE = 0x100A;
  static const DWORD PDERR_PRINTERNOTFOUND = 0x100B;
  static const DWORD PDERR_DEFAULTDIFFERENT = 0x100C;
  static const DWORD CFERR_NOFONTS = 0x2001;
  static const DWORD CFERR_MAXLESSTHANMIN = 0x2002;
  static const DWORD FNERR_SUBCLASSFAILURE = 0x3001;
  static const DWORD FNERR_BUFFERTOOSMALL = 0x3003;
  static const DWORD FNERR_INVALIDFILENAME = 0x3002;
  static const DWORD FRERR_BUFFERLENGTHZERO = 0x4001;
]]
