require( 'ffi/winapi/headers/windows' )
local ffi = require( 'ffi' )
ffi.cdef [[
  DWORD DhcpAddFilterV4(                       DHCP_CONST WCHAR* ServerIpAddress, DHCP_FILTER_ADD_INFO* AddFilterInfo, BOOL ForceFlag);
  DWORD DhcpAddServer(                         DWORD Flags, LPVOID IdInfo, LPDHCP_SERVER_INFO NewServer, LPVOID CallbackFn, LPVOID CallbackData);
  DWORD DhcpAddSubnetElementV5(                DHCP_CONST WCHAR* ServerIpAddress, DHCP_IP_ADDRESS SubnetAddress, DHCP_CONST DHCP_SUBNET_ELEMENT_DATA_V5* AddElementInfo);
  DWORD DhcpAuditLogGetParams(                 LPWSTR ServerIpAddress, DWORD Flags, LPWSTR* AuditLogDir, DWORD* DiskCheckInterval, DWORD* MaxLogFilesSize, DWORD* MinSpaceOnDisk);
  DWORD DhcpAuditLogSetParams(                 LPWSTR ServerIpAddress, DWORD Flags, LPWSTR AuditLogDir, DWORD DiskCheckInterval, DWORD MaxLogFilesSize, DWORD MinSpaceOnDisk);
  DWORD DhcpCreateClass(                       LPWSTR ServerIpAddress, DWORD ReservedMustBeZero, LPDHCP_CLASS_INFO ClassInfo);
  DWORD DhcpCreateClientInfo(                  DHCP_CONST WCHAR* ServerIpAddress, DHCP_CONST DHCP_CLIENT_INFO* ClientInfo);
  DWORD DhcpCreateClientInfoV4(                DHCP_CONST WCHAR* ServerIpAddress, DHCP_CONST DHCP_CLIENT_INFO_V4* ClientInfo);
  DWORD DhcpCreateClientInfoVQ(                DHCP_CONST WCHAR* ServerIpAddress, LPDHCP_CLIENT_INFO_VQ ClientInfo);
  DWORD DhcpCreateOptionV5(                    LPWSTR ServerIpAddress, DWORD Flags, DHCP_OPTION_ID OptionId, LPWSTR ClassName, LPWSTR VendorName, LPDHCP_OPTION OptionInfo);
  DWORD DhcpCreateSubnet(                      DHCP_CONST WCHAR* ServerIpAddress, DHCP_IP_ADDRESS SubnetAddress, DHCP_CONST DHCP_SUBNET_INFO* SubnetInfo);
  DWORD DhcpCreateSubnetVQ(                    WCHAR* ServerIpAddress, DHCP_IP_ADDRESS SubnetAddress, DHCP_CONST DHCP_SUBNET_INFO_VQ* SubnetInfo);
  DWORD DhcpDeleteClass(                       LPWSTR ServerIpAddress, DWORD ReservedMustBeZero, LPWSTR ClassName);
  DWORD DhcpDeleteClientInfo(                  DHCP_CONST WCHAR* ServerIpAddress, DHCP_CONST DHCP_SEARCH_INFO* ClientInfo);
  DWORD DhcpDeleteFilterV4(                    DHCP_CONST WCHAR* ServerIpAddress, DHCP_ADDR_PATTERN* DeleteFilterInfo);
  DWORD DhcpDeleteServer(                      DWORD Flags, LPVOID IdInfo, LPDHCP_SERVER_INFO NewServer, LPVOID CallbackFn, LPVOID CallbackData);
  DWORD DhcpDeleteSubnet(                      DHCP_CONST WCHAR* ServerIpAddress, DHCP_IP_ADDRESS SubnetAddress, DHCP_FORCE_FLAG ForceFlag);
  DWORD DhcpDeleteSuperScopeV4(                DHCP_CONST WCHAR* ServerIpAddress, DHCP_CONST LPWSTR SuperScopeName);
  VOID  DhcpDsCleanup(                         );
  DWORD DhcpDsInit(                            );
  DWORD DhcpEnumClasses(                       LPWSTR ServerIpAddress, DWORD ReservedMustBeZero, DHCP_RESUME_HANDLE* ResumeHandle, DWORD PreferredMaximum, LPDHCP_CLASS_INFO_ARRAY* ClassInfoArray, DWORD* nRead, DWORD* nTotal);
  DWORD DhcpEnumFilterV4(                      DHCP_CONST WCHAR* ServerIpAddress, LPDHCP_ADDR_PATTERN ResumeHandle, DWORD PreferrredMaximum, DHCP_FILTER_LIST_TYPE ListType, LPDHCP_FILTER_ENUM_INFO* EnumFilterInfo, DWORD* ElementsRead, DWORD* ElementsTotal);
  DWORD DhcpEnumOptionsV5(                     LPWSTR ServerIpAddress, DWORD Flags, LPWSTR ClassName, LPWSTR VendorName, DHCP_RESUME_HANDLE* ResumeHandle, DWORD PreferredMaximum, LPDHCP_OPTION_ARRAY* Options, DWORD* OptionsRead, DWORD* OptionsTotal);
  DWORD DhcpEnumOptionValuesV5(                LPWSTR ServerIpAddress, DWORD Flags, LPWSTR ClassName, LPWSTR VendorName, LPDHCP_OPTION_SCOPE_INFO ScopeInfo, DHCP_RESUME_HANDLE* ResumeHandle, DWORD PreferredMaximum, LPDHCP_OPTION_VALUE_ARRAY* OptionValues, DWORD* OptionsRead, DWORD* OptionsTotal);
  DWORD DhcpEnumServers(                       DWORD Flags, LPVOID IdInfo, LPDHCP_SERVER_INFO_ARRAY* Servers, LPVOID CallbackFn, LPVOID CallbackData);
  DWORD DhcpEnumSubnetClients(                 DHCP_CONST WCHAR* ServerIpAddress, DHCP_IP_ADDRESS SubnetAddress, DHCP_RESUME_HANDLE* ResumeHandle, DWORD PreferredMaximum, LPDHCP_CLIENT_INFO_ARRAY* ClientInfo, DWORD* ClientsRead, DWORD* ClientsTotal);
  DWORD DhcpEnumSubnetClientsV5(               DHCP_CONST WCHAR* ServerIpAddress, DHCP_IP_ADDRESS SubnetAddress, DHCP_RESUME_HANDLE* ResumeHandle, DWORD PreferredMaximum, LPDHCP_CLIENT_INFO_ARRAY_V5* ClientInfo, DWORD* ClientsRead, DWORD* ClientsTotal);
  DWORD DhcpEnumSubnetClientsVQ(               DHCP_CONST WCHAR* ServerIpAddress, DHCP_IP_ADDRESS SubnetAddress, DHCP_RESUME_HANDLE* ResumeHandle, DWORD PreferredMaximum, LPDHCP_CLIENT_INFO_ARRAY_VQ* ClientInfo, DWORD* ClientsRead, DWORD* ClientsTotal);
  DWORD DhcpEnumSubnetClientsFilterStatusInfo( DHCP_CONST WCHAR* ServerIpAddress, DHCP_IP_ADDRESS SubnetAddress, DHCP_RESUME_HANDLE* ResumeHandle, DWORD PreferredMaximum, LPDHCP_CLIENT_FILTER_STATUS_INFO_ARRAY* ClientInfo, DWORD* ClientsRead, DWORD* ClientsTotal);
  DWORD DhcpEnumSubnetElementsV5(              DHCP_CONST WCHAR* ServerIpAddress, DHCP_IP_ADDRESS SubnetAddress, DHCP_SUBNET_ELEMENT_TYPE EnumElementType, DHCP_RESUME_HANDLE* ResumeHandle, DWORD PreferredMaximum, LPDHCP_SUBNET_ELEMENT_INFO_ARRAY* EnumElementInfo, DWORD* ElementsRead, DWORD* ElementsTotal);
  DWORD DhcpEnumSubnets(                       DHCP_CONST WCHAR* ServerIpAddress, DHCP_RESUME_HANDLE* ResumeHandle, DWORD PreferredMaximum, LPDHCP_IP_ARRAY* EnumInfo, DWORD* ElementsRead, DWORD* ElementsTotal);
  DWORD DhcpGetAllOptionValues(                LPWSTR ServerIpAddress, DWORD Flags, LPDHCP_OPTION_SCOPE_INFO ScopeInfo, LPDHCP_ALL_OPTION_VALUES* Values);
  DWORD DhcpGetClassInfo(                      LPWSTR ServerIpAddress, DWORD ReservedMustBeZero, LPDHCP_CLASS_INFO PartialClassInfo, LPDHCP_CLASS_INFO* FilledClassInfo);
  DWORD DhcpGetClientInfo(                     DHCP_CONST WCHAR* ServerIpAddress, DHCP_CONST DHCP_SEARCH_INFO* SearchInfo, LPDHCP_CLIENT_INFO* ClientInfo);
  DWORD DhcpGetClientInfoV4(                   DHCP_CONST WCHAR* ServerIpAddress, DHCP_CONST DHCP_SEARCH_INFO* SearchInfo, LPDHCP_CLIENT_INFO_V4* ClientInfo);
  DWORD DhcpGetClientInfoVQ(                   DHCP_CONST WCHAR* ServerIpAddress, LPDHCP_SEARCH_INFO SearchInfo, LPDHCP_CLIENT_INFO_VQ ClientInfo);
  DWORD DhcpGetFilterV4(                       DHCP_CONST WCHAR* ServerIpAddress, DHCP_FILTER_GLOBAL_INFO* GlobalFilterInfo);
  DWORD DhcpGetMibInfoV5(                      WCHAR* ServerIpAddress, LPDHCP_MIB_INFO_V5* MibInfo);
  DWORD DhcpGetOptionInfoV5(                   LPWSTR ServerIpAddress, DWORD Flags, DHCP_OPTION_ID OptionID, LPWSTR ClassName, LPWSTR VendorName, LPDHCP_OPTION* OptionInfo);
  DWORD DhcpGetOptionValue(                    DHCP_CONST WCHAR* ServerIpAddress, DHCP_OPTION_ID OptionID, DHCP_CONST DHCP_OPTION_SCOPE_INFO* ScopeInfo, LPDHCP_OPTION_VALUE* OptionValue);
  DWORD DhcpGetOptionValueV5(                  LPWSTR ServerIpAddress, DWORD Flags, DHCP_OPTION_ID OptionID, LPWSTR ClassName, LPWSTR VendorName, LPDHCP_OPTION_SCOPE_INFO ScopeInfo, LPDHCP_OPTION_VALUE* OptionValue);
  DWORD DhcpGetServerBindingInfo(              DHCP_CONST WCHAR* ServerIpAddress, ULONG Flags, LPDHCP_BIND_ELEMENT_ARRAY* BindElementsInfo);
  DWORD DhcpGetSubnetDelayOffer(               LPWSTR ServerIpAddress, DHCP_IP_ADDRESS SubnetAddress, USHORT* TimeDelayInMilliseconds);
  DWORD DhcpGetSubnetInfo(                     DHCP_CONST WCHAR* ServerIpAddress, DHCP_IP_ADDRESS SubnetAddress, LPDHCP_SUBNET_INFO* SubnetInfo);
  DWORD DhcpGetSubnetInfoVQ(                   DHCP_CONST WCHAR* ServerIpAddress, DHCP_IP_ADDRESS SubnetAddress, LPDHCP_SUBNET_INFO_VQ* SubnetInfo);
  DWORD DhcpGetSuperScopeInfoV4(               DHCP_CONST WCHAR* ServerIpAddress, LPDHCP_SUPER_SCOPE_TABLE* SuperScopeTable);
  DWORD DhcpGetVersion(                        LPWSTR ServerIpAddress, LPDWORD MajorVersion, LPDWORD MinorVersion);
  DWORD DhcpModifyClass(                       LPWSTR ServerIpAddress, DWORD ReservedMustBeZero, LPDHCP_CLASS_INFO ClassInfo);
  DWORD DhcpRemoveOptionV5(                    LPWSTR ServerIpAddress, DWORD Flags, DHCP_OPTION_ID OptionID, LPWSTR ClassName, LPWSTR VendorName);
  DWORD DhcpRemoveOptionValueV5(               LPWSTR ServerIpAddress, DWORD Flags, DHCP_OPTION_ID OptionID, LPWSTR ClassName, LPWSTR VendorName, LPDHCP_OPTION_SCOPE_INFO ScopeInfo);
  DWORD DhcpRemoveSubnetElementV5(             DHCP_CONST WCHAR* ServerIpAddress, DHCP_IP_ADDRESS SubnetAddress, DHCP_CONST DHCP_SUBNET_ELEMENT_DATA_V5* RemoveElementInfo, DHCP_FORCE_FLAG ForceFlag);
  VOID  DhcpRpcFreeMemory(                     PVOID BufferPointer);
  DWORD DhcpServerGetConfigVQ(                 DHCP_CONST WCHAR* ServerIpAddress, LPDHCP_SERVER_CONFIG_INFO_VQ* ConfigInfo);
  DWORD DhcpServerQueryDnsRegCredentials(      LPWSTR ServerIpAddress, ULONG UnameSize, LPWSTR Uname, ULONG DomainSize, LPWSTR Domain);
  DWORD DhcpServerRedoAuthorization(           LPWSTR ServerIpAddr, ULONG dwReserved);
  DWORD DhcpServerSetConfigV4(                 DHCP_CONST WCHAR* ServerIpAddress, DWORD FieldsToSet, LPDHCP_SERVER_CONFIG_INFO_V4 ConfigInfo);
  DWORD DhcpServerSetConfigVQ(                 DHCP_CONST WCHAR* ServerIpAddress, DWORD FieldsToSet, LPDHCP_SERVER_CONFIG_INFO_VQ ConfigInfo);
  DWORD DhcpServerSetDnsRegCredentialsV5(      LPWSTR ServerIpAddress, LPWSTR Uname, LPWSTR Domain, LPWSTR Password);
  DWORD DhcpSetClientInfo(                     DHCP_CONST WCHAR* ServerIpAddress, DHCP_CONST DHCP_CLIENT_INFO* ClientInfo);
  DWORD DhcpSetClientInfoV4(                   DHCP_CONST WCHAR* ServerIpAddress, DHCP_CONST DHCP_CLIENT_INFO_V4* ClientInfo);
  DWORD DhcpSetClientInfoVQ(                   DHCP_CONST WCHAR* ServerIpAddress, LPDHCP_CLIENT_INFO_VQ ClientInfo);
  DWORD DhcpSetFilterV4(                       DHCP_CONST WCHAR* ServerIpAddress, DHCP_FILTER_GLOBAL_INFO* GlobalFilterInfo);
  DWORD DhcpSetOptionInfoV5(                   LPWSTR ServerIpAddress, DWORD Flags, DHCP_OPTION_ID OptionID, LPWSTR* ClassName, LPWSTR* VendorName, LPDHCP_OPTION OptionInfo);
  DWORD DhcpSetOptionValueV5(                  LPWSTR ServerIpAddress, DWORD Flags, DHCP_OPTION_ID OptionId, LPWSTR ClassName, LPWSTR VendorName, LPDHCP_OPTION_SCOPE_INFO ScopeInfo, LPDHCP_OPTION_DATA OptionValue);
  DWORD DhcpSetServerBindingInfo(              DHCP_CONST WCHAR* ServerIpAddress, ULONG Flags, LPDHCP_BIND_ELEMENT_ARRAY BindElementInfo);
  DWORD DhcpSetSubnetDelayOffer(               LPWSTR ServerIpAddress, DHCP_IP_ADDRESS SubnetAddress, USHORT TimeDelayInMilliseconds);
  DWORD DhcpSetSubnetInfo(                     DHCP_CONST WCHAR* ServerIpAddress, DHCP_IP_ADDRESS SubnetAddress, DHCP_CONST DHCP_SUBNET_INFO* SubnetInfo);
  DWORD DhcpSetSubnetInfoVQ(                   DHCP_CONST WCHAR* ServerIpAddress, DHCP_IP_ADDRESS SubnetAddress, DHCP_CONST DHCP_SUBNET_INFO_VQ* SubnetInfo);
  DWORD DhcpSetSuperScopeV4(                   DHCP_CONST WCHAR* ServerIpAddress, DHCP_CONST DHCP_IP_ADDRESS SubnetAddress, DHCP_CONST LPWSTR SuperScopeName, DHCP_CONST BOOL ChangeExisting);
  DWORD DhcpAddSubnetElementV6(                LPWSTR ServerIpAddress, DHCP_IPV6_ADDRESS SubnetAddress, LPDHCP_SUBNET_ELEMENT_DATA_V6 AddElementInfo);
  DWORD DhcpCreateClassV6(                     LPWSTR ServerIpAddress, DWORD ReservedMustBeZero, LPDHCP_CLASS_INFO_V6 ClassInfo);
  DWORD DhcpCreateOptionV6(                    LPWSTR ServerIpAddress, DWORD Flags, DHCP_OPTION_ID OptionId, WCHAR* ClassName, WCHAR* VendorName, LPDHCP_OPTION OptionInfo);
  DWORD DhcpCreateSubnetV6(                    LPWSTR ServerIpAddress, DHCP_IPV6_ADDRESS SubnetAddress, LPDHCP_SUBNET_INFO_V6* SubnetInfo);
  DWORD DhcpDeleteClassV6(                     LPWSTR ServerIpAddress, DWORD ReservedMustBeZero, LPWSTR ClassName);
  DWORD DhcpDeleteClientInfoV6(                LPWSTR ServerIpAddress, LPDHCP_SEARCH_INFO_V6 ClientInfo);
  DWORD DhcpDeleteSubnetV6(                    LPWSTR ServerIpAddress, DHCP_IPV6_ADDRESS SubnetAddress, DHCP_FORCE_FLAG ForceFlag);
  DWORD DhcpEnumClassesV6(                     LPWSTR ServerIpAddress, DWORD ReservedMustBeZero, DHCP_RESUME_HANDLE* ResumeHandle, DWORD PreferredMaximum, LPDHCP_CLASS_INFO_ARRAY_V6* ClassInfoArray, DWORD* nRead, DWORD* nTotal);
  DWORD DhcpEnumOptionsV6(                     LPWSTR ServerIpAddress, DWORD Flags, WCHAR* ClassName, WCHAR* VendorName, DHCP_RESUME_HANDLE* ResumeHandle, DWORD PreferredMaximum, LPDHCP_OPTION_ARRAY* Options, DWORD* OptionsRead, DWORD* OptionsTotal);
  DWORD DhcpEnumOptionValuesV6(                LPWSTR ServerIpAddress, DWORD Flags, WCHAR* ClassName, WCHAR* VendorName, LPDHCP_OPTION_SCOPE_INFO6 ScopeInfo, DHCP_RESUME_HANDLE* ResumeHandle, DWORD PreferredMaximum, LPDHCP_OPTION_VALUE_ARRAY* OptionValues, DWORD* OptionsRead, DWORD* OptionsTotal);
  DWORD DhcpEnumSubnetsV6(                     LPWSTR ServerIpAddress, DHCP_RESUME_HANDLE* ResumeHandle, DWORD PreferredMaximum, LPDHCPV6_IP_ARRAY* EnumInfo, DWORD* ElementsRead, DWORD* ElementsTotal);
  DWORD DhcpEnumSubnetClientsV6(               LPWSTR ServerIpAddress, DHCP_IPV6_ADDRESS SubnetAddress, DHCP_RESUME_IPV6_HANDLE* ResumeHandle, DWORD PreferredMaximum, LPDHCP_CLIENT_INFO_ARRAY_V6* ClientInfo, DWORD* ClientsRead, DWORD* ClientsTotal);
  DWORD DhcpEnumSubnetElementsV6(              LPWSTR ServerIpAddress, DHCP_IPV6_ADDRESS SubnetAddress, DHCP_SUBNET_ELEMENT_TYPE_V6 EnumElementType, DHCP_RESUME_HANDLE* ResumeHandle, DWORD PreferredMaximum, LPDHCP_SUBNET_ELEMENT_INFO_ARRAY_V6* EnumElementInfo, DWORD* ElementsRead, DWORD* ElementsTotal);
  DWORD DhcpGetAllOptionsV6(                   LPWSTR ServerIpAddress, DWORD Flags, LPDHCP_ALL_OPTIONS* OptionStruct);
  DWORD DhcpGetAllOptionValuesV6(              LPWSTR ServerIpAddress, DWORD Flags, LPDHCP_OPTION_SCOPE_INFO6 ScopeInfo, LPDHCP_ALL_OPTION_VALUES* Values);
  DWORD DhcpGetClientInfoV6(                   DHCP_CONST WCHAR* ServerIpAddress, DHCP_CONST DHCP_SEARCH_INFO_V6* SearchInfo, LPDHCP_CLIENT_INFO_V6* ClientInfo);
  DWORD DhcpGetMibInfoV6(                      DHCP_CONST WCHAR* ServerIpAddress, LPDHCP_MIB_INFO_V6* MibInfo);
  DWORD DhcpGetOptionInfoV6(                   LPWSTR ServerIpAddress, DWORD Flags, DHCP_OPTION_ID OptionID, WCHAR* ClassName, WCHAR* VendorName, LPDHCP_OPTION* OptionInfo);
  DWORD DhcpGetOptionValueV6(                  LPWSTR ServerIpAddress, DWORD Flags, DHCP_OPTION_ID OptionID, WCHAR* ClassName, WCHAR* VendorName, LPDHCP_OPTION_SCOPE_INFO6* ScopeInfo, LPDHCP_OPTION_VALUE OptionValue);
  DWORD DhcpGetServerBindingInfoV6(            DHCP_CONST WCHAR* ServerIpAddress, ULONG Flags, LPDHCPV6_BIND_ELEMENT_ARRAY* BindElementsInfo);
  DWORD DhcpGetSubnetInfoV6(                   LPWSTR ServerIpAddress, DHCP_IPV6_ADDRESS SubnetAddress, LPDHCP_SUBNET_INFO_V6* SubnetInfo);
  DWORD DhcpModifyClassV6(                     LPWSTR ServerIpAddress, DWORD ReservedMustBeZero, LPDHCP_CLASS_INFO_V6 ClassInfo);
  DWORD DhcpRemoveOptionV6(                    LPWSTR ServerIpAddress, DWORD Flags, DHCP_OPTION_ID OptionID, WCHAR* ClassName, WCHAR* VendorName);
  DWORD DhcpRemoveOptionValueV6(               LPWSTR ServerIpAddress, DWORD Flags, DHCP_OPTION_ID OptionID, WCHAR* ClassName, WCHAR* VendorName, LPDHCP_OPTION_SCOPE_INFO6 ScopeInfo);
  DWORD DhcpRemoveSubnetElementV6(             LPWSTR ServerIpAddress, DHCP_IPV6_ADDRESS SubnetAddress, LPDHCP_SUBNET_ELEMENT_DATA_V6 RemoveElementInfo, DHCP_FORCE_FLAG ForceFlag);
  DWORD DhcpServerGetConfigV6(                 DHCP_CONST WCHAR* ServerIpAddress, LPDHCP_OPTION_SCOPE_INFO6 ScopeInfo, LPDHCP_SERVER_CONFIG_INFO_V6* ConfigInfo);
  DWORD DhcpSetClientInfoV6(                   LPWSTR ServerIpAddress, LPDHCP_CLIENT_INFO_V6 ClientInfo);
  DWORD DhcpSetOptionInfoV6(                   LPWSTR ServerIpAddress, DWORD Flags, DHCP_OPTION_ID OptionID, WCHAR* ClassName, WCHAR* VendorName, LPDHCP_OPTION OptionInfo);
  DWORD DhcpSetOptionValueV6(                  LPWSTR ServerIpAddress, DWORD Flags, DHCP_OPTION_ID OptionId, WCHAR* ClassName, WCHAR* VendorName, LPDHCP_OPTION_SCOPE_INFO6 ScopeInfo, LPDHCP_OPTION_DATA OptionValue);
  DWORD DhcpSetServerBindingInfoV6(            DHCP_CONST WCHAR* ServerIpAddress, ULONG Flags, LPDHCPV6_BIND_ELEMENT_ARRAY BindElementsInfo);
  DWORD DhcpServerSetConfigV6(                 DHCP_CONST WCHAR* ServerIpAddress, LPDHCP_OPTION_SCOPE_INFO6 ScopeInfo, DWORD FieldsToSet, LPDHCP_SERVER_CONFIG_INFO_V6 ConfigInfo);
  DWORD DhcpSetSubnetInfoV6(                   DHCP_CONST WCHAR* ServerIpAddress, DHCP_IPV6_ADDRESS SubnetAddress, LPDHCP_SUBNET_INFO_V6 SubnetInfo);
]]
return ffi.load( 'Dhcpsapi.dll' )
