require( 'ffi/winapi/headers/windows' )
require( 'ffi/winapi/headers/cryptography' )
require( 'ffi/winapi/headers/registry' )
local ffi = require( 'ffi' )
ffi.cdef [[
  INSTALLUILEVEL    MsiSetInternalUI(               INSTALLUILEVEL dwUILevel, HWND* phWnd);
  INSTALLUI_HANDLER MsiSetExternalUI(               INSTALLUI_HANDLER puiHandler, WINAPI_MsiInstallLogMode dwMessageFilter, LPVOID pvContext);
  WINAPI_MSI_ERROR  MsiSetExternalUIRecord(         PINSTALLUI_HANDLER_RECORD puiHandler, WINAPI_MsiInstallLogMode dwMessageFilter, LPVOID pvContext, PINSTALLUI_HANDLER_RECORD ppuiPrevHandler);
  WINAPI_MSI_ERROR  MsiEnableLog(                   WINAPI_MsiInstallLogMode dwLogMode, LPCTSTR szLogFile, WINAPI_MsiInstallLogAttributes dwLogAttributes);
  WINAPI_MSI_ERROR  MsiCloseHandle(                 MSIHANDLE hAny);
  UINT              MsiCloseAllHandles(             );
  WINAPI_MSI_ERROR  MsiAdvertiseProduct(            LPCTSTR szPackagePath, LPCTSTR szScriptfilePath, LPCTSTR szTransforms, LANGID lgidLanguage);
  WINAPI_MSI_ERROR  MsiAdvertiseProductEx(          LPCTSTR szPackagePath, LPCTSTR szScriptfilePath, LPCTSTR szTransforms, LANGID lgidLanguage, WINAPI_MsiArchFlags dwPlatform, WINAPI_MsiAdOptions dwOptions);
  WINAPI_MSI_ERROR  MsiAdvertiseScript(             LPCTSTR szScriptFile, WINAPI_MsiScriptFlags dwFlags, PHKEY phRegData, BOOL fRemoveItems);
  WINAPI_MSI_ERROR  MsiInstallProduct(              LPCTSTR szPackagePath, LPCTSTR szCommandLine);
  WINAPI_MSI_ERROR  MsiConfigureProduct(            LPCTSTR szProduct, WINAPI_MsiInstallLevel iInstallLevel, INSTALLSTATE eInstallState);
  WINAPI_MSI_ERROR  MsiConfigureProductEx(          LPCTSTR szProduct, WINAPI_MsiInstallLevel iInstallLevel, INSTALLSTATE eInstallState, LPCTSTR szCommandLine);
  WINAPI_MSI_ERROR  MsiReinstallProduct(            LPCTSTR szProduct, WINAPI_MsiReinstallMode dwReinstallMode);
  WINAPI_MSI_ERROR  MsiConfigureFeature(            LPCTSTR szProduct, LPCTSTR szFeature, INSTALLSTATE eInstallState);
  WINAPI_MSI_ERROR  MsiReinstallFeature(            LPCTSTR szProduct, LPCTSTR szFeature, WINAPI_MsiReinstallMode dwReinstallMode);
  WINAPI_MSI_ERROR  MsiInstallMissingComponent(     LPCTSTR szProduct, LPCTSTR szComponent, INSTALLSTATE eInstallState);
  WINAPI_MSI_ERROR  MsiInstallMissingFile(          LPCTSTR szProduct, LPCTSTR szFile);
  WINAPI_MSI_ERROR  MsiNotifySidChange(             LPCTSTR szOldSid, LPCTSTR szNewSid);
  WINAPI_MSI_ERROR  MsiProcessAdvertiseScript(      LPCTSTR szScriptFile, LPCTSTR szIconFolder, HKEY hRegData, BOOL fShortcuts, BOOL fRemoveItems);
  WINAPI_MSI_ERROR  MsiSourceListAddSource(         LPCTSTR szProduct, LPCTSTR szUserName, DWORD dwReserved, LPCTSTR szSource);
  WINAPI_MSI_ERROR  MsiSourceListAddSourceEx(       LPCTSTR szProductCodeOrPatchCode, LPCTSTR szUserSid, MSIINSTALLCONTEXT dwContext, WINAPI_MsiSourceType dwOptions, LPCTSTR szSource, DWORD dwIndex);
  WINAPI_MSI_ERROR  MsiSourceListClearSource(       LPCTSTR szProductCodeOrPatchCode, LPCTSTR szUserSid, MSIINSTALLCONTEXT dwContext, WINAPI_MsiSourceType dwOptions, LPCTSTR szSource);
  WINAPI_MSI_ERROR  MsiSourceListClearAll(          LPCTSTR szProduct, LPCTSTR szUserName, DWORD dwReserved);
  WINAPI_MSI_ERROR  MsiSourceListClearAllEx(        LPCTSTR szProductCodeOrPatchCode, LPCTSTR szUserSid, MSIINSTALLCONTEXT dwContext, WINAPI_MsiSourceType dwOptions);
  WINAPI_MSI_ERROR  MsiSourceListForceResolution(   LPCTSTR szProduct, LPCTSTR szUserName, DWORD dwReserved);
  WINAPI_MSI_ERROR  MsiSourceListForceResolutionEx( LPCTSTR szProductCodeOrPatchCode, LPCTSTR szUserSid, MSIINSTALLCONTEXT dwContext, WINAPI_MsiCode dwOptions);
  WINAPI_MSI_ERROR  MsiSourceListGetInfo(           LPCTSTR szProductCodeOrPatchCode, LPCTSTR szUserSid, MSIINSTALLCONTEXT dwContext, WINAPI_MsiCode dwOptions, LPCTSTR szProperty, LPTSTR szValue, LPDWORD pcchValue);
  WINAPI_MSI_ERROR  MsiSourceListSetInfo(           LPCTSTR szProductCodeOrPatchCode, LPCTSTR szUserSid, MSIINSTALLCONTEXT dwContext, WINAPI_MsiSourceType dwOptions, LPCTSTR szProperty, LPCTSTR szValue);
  WINAPI_MSI_ERROR  MsiSourceListEnumMediaDisks(    LPCTSTR szProductCodeOrPatchCode, LPCTSTR szUserSID, MSIINSTALLCONTEXT dwContext, WINAPI_MsiCode dwOptions, DWORD dwIndex, LPWORD pdwDiskId, LPTSTR szVolumeLabel, LPDWORD pcchVolumeLabel, LPTSTR szDiskPrompt, LPDWORD pcchDiskPrompt);
  WINAPI_MSI_ERROR  MsiSourceListAddMediaDisk(      LPCTSTR szProductCodeOrPatchCode, LPCTSTR szUserSid, MSIINSTALLCONTEXT dwContext, WINAPI_MsiCode dwOptions, DWORD dwDiskId, LPCTSTR szVolumeLabel, LPCTSTR szDiskPrompt);
  WINAPI_MSI_ERROR  MsiSourceListClearMediaDisk(    LPCTSTR szProductCodeOrPatchCode, LPCTSTR szUserSid, MSIINSTALLCONTEXT dwContext, WINAPI_MsiCode dwOptions, DWORD dwDiskID);
  WINAPI_MSI_ERROR  MsiSourceListEnumSources(       LPCTSTR szProductCodeOrPatchCode, LPCTSTR szUserSid, MSIINSTALLCONTEXT dwContext, WINAPI_MsiSourceType dwOptions, DWORD dwIndex, LPTSTR szSource, LPDWORD pcchSource);
  WINAPI_MSI_ERROR  MsiProvideAssembly(             LPCTSTR szAssemblyName, LPCTSTR szAppContext, WINAPI_MsiInstallMode dwInstallMode, WINAPI_MsiAssemblyInfo dwAssemblyInfo, LPTSTR lpPathBuf, DWORD* pcchPathBuf);
  WINAPI_MSI_ERROR  MsiProvideComponent(            LPCTSTR szProduct, LPCTSTR szFeature, LPCTSTR szComponent, WINAPI_MsiInstallMode dwInstallMode, LPTSTR lpPathBuf, DWORD* pcchPathBuf);
  WINAPI_MSI_ERROR  MsiProvideQualifiedComponent(   LPCTSTR szComponent, LPCTSTR szQualifier, WINAPI_MsiInstallMode dwInstallMode, LPTSTR lpPathBuf, DWORD* pcchPathBuf);
  WINAPI_MSI_ERROR  MsiProvideQualifiedComponentEx( LPCTSTR szComponent, LPCTSTR szQualifier, WINAPI_MsiInstallMode dwInstallMode, LPTSTR szProduct, DWORD dwUnused1, DWORD dwUnused2, LPTSTR lpPathBuf, DWORD* pcchPathBuf);
  INSTALLSTATE      MsiGetComponentPath(            LPCTSTR szProduct, LPCTSTR szComponent, LPTSTR lpPathBuf, DWORD* pcchBuf);
  INSTALLSTATE      MsiGetComponentPathEx(          LPCTSTR szProductCode, LPCTSTR szComponentCode, LPCTSTR szUserSid, MSIINSTALLCONTEXT dwContext, LPTSTR szPathBuf, LPDWORD pcchBuf);
  INSTALLSTATE      MsiLocateComponent(             LPCTSTR szComponent, LPTSTR lpPathBuf, DWORD* pcchBuf);
  WINAPI_MSI_ERROR  MsiQueryComponentState(         LPTSTR szProductCode, LPTSTR szUserSid, MSIINSTALLCONTEXT dwContext, LPCTSTR szComponent, INSTALLSTATE* pdwState);
  WINAPI_MSI_ERROR  MsiCollectUserInfo(             LPCTSTR szProduct);
  INSTALLSTATE      MsiUseFeature(                  LPCTSTR szProduct, LPCTSTR szFeature);
  INSTALLSTATE      MsiUseFeatureEx(                LPCTSTR szProduct, LPCTSTR szFeature, WINAPI_MsiInstallMode dwInstallMode, DWORD dwReserved);
  WINAPI_MSI_ERROR  MsiGetProductCode(              LPCTSTR szComponent, LPTSTR lpProductBuf);
  WINAPI_MSI_ERROR  MsiEnumProducts(                DWORD iProductIndex, LPTSTR lpProductBuf);
  WINAPI_MSI_ERROR  MsiEnumProductsEx(              LPCTSTR szProductCode, LPCTSTR szUserSid, MSIINSTALLCONTEXT dwContext, DWORD dwIndex, TCHAR [39] szInstalledProductCode, MSIINSTALLCONTEXT* pdwInstalledContext, LPTSTR szSid, LPDWORD pcchSid);
  WINAPI_MSI_ERROR  MsiEnumRelatedProducts(         LPCTSTR lpUpgradeCode, DWORD dwReserved, DWORD iProductIndex, LPTSTR lpProductBuf);
  WINAPI_MSI_ERROR  MsiEnumFeatures(                LPCTSTR szProduct, DWORD iFeatureIndex, LPTSTR lpFeatureBuf, LPTSTR lpParentBuf);
  WINAPI_MSI_ERROR  MsiEnumComponents(              DWORD iComponentIndex, LPTSTR lpComponentBuf);
  WINAPI_MSI_ERROR  MsiEnumComponentsEx(            LPCTSTR szUserSid, MSIINSTALLCONTEXT dwContext, DWORD dwIndex, TCHAR [39] szInstalledComponentCode, MSIINSTALLCONTEXT* pdwInstalledContext, LPTSTR szSid, LPDWORD pcchSid);
  WINAPI_MSI_ERROR  MsiEnumClients(                 LPCTSTR szComponent, DWORD iProductIndex, LPTSTR lpProductBuf);
  WINAPI_MSI_ERROR  MsiEnumClientsEx(               LPCTSTR szComponent, LPCTSTR szUserSid, MSIINSTALLCONTEXT dwContext, DWORD dwProductIndex, TCHAR [39] szProductBuf, MSIINSTALLCONTEXT* pdwInstalledContext, LPTSTR szSid, LPDWORD pcchSid);
  WINAPI_MSI_ERROR  MsiEnumComponentQualifiers(     LPTSTR szComponent, DWORD iIndex, LPTSTR lpQualifierBuf, DWORD* pcchQualifierBuf, LPTSTR lpApplicationDataBuf, DWORD* pcchApplicationDataBuf);
  INSTALLSTATE      MsiQueryFeatureState(           LPCTSTR szProduct, LPCTSTR szFeature);
  WINAPI_MSI_ERROR  MsiQueryFeatureStateEx(         LPTSTR szProductCode, LPTSTR szUserSid, MSIINSTALLCONTEXT dwContext, LPCTSTR szFeature, INSTALLSTATE* pdwState);
  INSTALLSTATE      MsiQueryProductState(           LPCTSTR szProduct);
  WINAPI_MSI_ERROR  MsiGetFeatureUsage(             LPCTSTR szProduct, LPCTSTR szFeature, DWORD* pdwUseCount, WORD* pwDateUsed);
  WINAPI_MSI_ERROR  MsiGetProductInfo(              LPCTSTR szProduct, LPCTSTR szProperty, LPTSTR lpValueBuf, DWORD* pcchValueBuf);
  WINAPI_MSI_ERROR  MsiGetProductInfoEx(            LPCTSTR szProductCode, LPCTSTR szUserSid, MSIINSTALLCONTEXT dwContext, LPCTSTR szProperty, LPTSTR lpValue, LPDWORD pcchValue);
  USERINFOSTATE     MsiGetUserInfo(                 LPCTSTR szProduct, LPTSTR lpUserNameBuf, DWORD* pcchUserNameBuf, LPTSTR lpOrgNameBuf, DWORD* pcchOrgNameBuf, LPTSTR lpSerialBuf, DWORD* pcchSerialBuf);
  WINAPI_MSI_ERROR  MsiOpenProduct(                 LPCTSTR szProduct, MSIHANDLE* hProduct);
  WINAPI_MSI_ERROR  MsiOpenPackage(                 LPCTSTR szPackagePath, MSIHANDLE* hProduct);
  WINAPI_MSI_ERROR  MsiOpenPackageEx(               LPCTSTR szPackagePath, WINAPI_MsiOpenPackageFlags dwOptions, MSIHANDLE* hProduct);
  WINAPI_MSI_ERROR  MsiIsProductElevated(           LPCTSTR szProductCode, BOOL* pfElevated);
  WINAPI_MSI_ERROR  MsiGetProductInfoFromScript(    LPCTSTR szScriptFile, LPTSTR lpProductBuf39, LANGID* plgidLanguage, DWORD* pdwVersion, LPTSTR lpNameBuf, DWORD* pcchNameBuf, LPTSTR lpPackageBuf, DWORD* pcchPackageBuf);
  WINAPI_MSI_ERROR  MsiGetProductProperty(          MSIHANDLE hProduct, LPCTSTR szProperty, LPTSTR lpValueBuf, DWORD* pcchValueBuf);
  WINAPI_MSI_ERROR  MsiGetShortcutTarget(           LPCTSTR szShortcutTarget, LPTSTR szProductCode, LPTSTR szFeatureId, LPTSTR szComponentCode);
  WINAPI_MSI_ERROR  MsiGetFeatureInfo(              MSIHANDLE hProduct, LPCTSTR szFeature, WINAPI_MsiInstallFeatureAttr* lpAttributes, LPTSTR lpTitleBuf, LPDWORD pcchTitleBuf, LPTSTR lpHelpBuf, LPDWORD pcchHelpBuf);
  WINAPI_MSI_ERROR  MsiVerifyPackage(               LPCTSTR szPackagePath);
  WINAPI_MSI_ERROR  MsiApplyPatch(                  LPCTSTR szPatchPackage, LPCTSTR szInstallPackage, INSTALLTYPE eInstallType, LPCTSTR szCommandLine);
  WINAPI_MSI_ERROR  MsiEnumPatches(                 LPCTSTR szProduct, DWORD iPatchIndex, LPTSTR lpPatchBuf, LPTSTR lpTransformsBuf, DWORD* pcchTransformsBuf);
  WINAPI_MSI_ERROR  MsiGetPatchInfo(                LPCTSTR szPatch, LPCTSTR szAttribute, LPTSTR lpValueBuf, DWORD* pcchValueBuf);
  WINAPI_MSI_ERROR  MsiRemovePatches(               LPCTSTR szPatchList, LPCTSTR szProductCode, INSTALLTYPE eUninstallType, LPCTSTR szPropertyList);
  WINAPI_MSI_ERROR  MsiDeterminePatchSequence(      LPCTSTR szProductCode, LPCTSTR szUserSid, MSIINSTALLCONTEXT dwContext, DWORD cPatchInfo, PMSIPATCHSEQUENCEINFO pPatchInfo);
  WINAPI_MSI_ERROR  MsiApplyMultiplePatches(        LPCTSTR szPatchPackages, LPCTSTR szProductCode, LPCTSTR szPropertiesList);
  WINAPI_MSI_ERROR  MsiEnumPatchesEx(               LPCTSTR szProductCode, LPCTSTR szUserSid, MSIINSTALLCONTEXT dwContext, WINAPI_MsiPatchState dwFilter, DWORD dwIndex, TCHAR [39] szPatchCode, TCHAR [39] szTargetProductCode, MSIINSTALLCONTEXT* pdwTargetProductContext, LPTSTR szTargetUserSid, LPDWORD pcchTargetUserSid);
  WINAPI_MSI_ERROR  MsiGetPatchFileList(            LPCTSTR szProductCode, LPCTSTR szPatchList, LPDWORD pcFiles, MSIHANDLE** pphFileRecords);
  WINAPI_MSI_ERROR  MsiGetPatchInfoEx(              LPCTSTR szPatchCode, LPCTSTR szProductCode, LPCTSTR szUserSid, MSIINSTALLCONTEXT dwContext, LPCTSTR szProperty, LPTSTR lpValue, DWORD* pcchValue);
  WINAPI_MSI_ERROR  MsiExtractPatchXMLData(         LPCTSTR szPatchPath, DWORD dwReserved, LPTSTR szXMLData, DWORD* pcchXMLData);
  WINAPI_MSI_ERROR  MsiDetermineApplicablePatches(  LPCTSTR szProductPackagePath, DWORD cPatchInfo, PMSIPATCHSEQUENCEINFO pPatchInfo);
  WINAPI_MSI_ERROR  MsiGetFileHash(                 LPCTSTR szFilePath, DWORD dwOptions, PMSIFILEHASHINFO pHash);
  HRESULT           MsiGetFileSignatureInformation( LPCTSTR szSignedObjectPath, WINAPI_MsiHashFlags dwFlags, PCCERT_CONTEXT* ppcCertContext, BYTE* pbHashData, DWORD* pcbHashData);
  WINAPI_MSI_ERROR  MsiGetFileVersion(              LPCTSTR szFilePath, LPTSTR lpVersionBuf, DWORD* pcchVersionBuf, LPTSTR lpLangBuf, DWORD* pcchLangBuf);
  WINAPI_MSI_ERROR  MsiBeginTransaction(            LPCWSTR szTransactionName, WINAPI_MsiTransactionAttributes dwTransactionAttributes, MSIHANDLE* hTransactionID, HANDLE* phChangeOfOwnerEvent);
  WINAPI_MSI_ERROR  MsiJoinTransaction(             MSIHANDLE hTransactionID, WINAPI_MsiTransactionAttributes dwTransactionAttributes, HANDLE* phChangeOfOwnerEvent);
  WINAPI_MSI_ERROR  MsiEndTransaction(              WINAPI_MsiTransactionState dwTransactionState);
  WINAPI_MSI_ERROR  MsiDatabaseCommit(              MSIHANDLE hDatabase);
  WINAPI_MSI_ERROR  MsiDatabaseGetPrimaryKeys(      MSIHANDLE hDatabase, LPCTSTR szTableName, MSIHANDLE* phRecord);
  MSICONDITION      MsiDatabaseIsTablePersistent(   MSIHANDLE hDatabase, LPCTSTR szTableName);
  WINAPI_MSI_ERROR  MsiDatabaseOpenView(            MSIHANDLE hDatabase, LPCTSTR szQuery, MSIHANDLE* phView);
  MSIHANDLE         MsiGetActiveDatabase(           MSIHANDLE hInstall);
  WINAPI_MSI_ERROR  MsiViewGetColumnInfo(           MSIHANDLE hView, MSICOLINFO eColumnInfo, MSIHANDLE* phRecord);
  WINAPI_MSI_ERROR  MsiOpenDatabase(                LPCTSTR szDatabasePath, LPCTSTR szPersist, MSIHANDLE* phDatabase);
  WINAPI_MSI_ERROR  MsiViewClose(                   MSIHANDLE hView);
  WINAPI_MSI_ERROR  MsiViewExecute(                 MSIHANDLE hView, MSIHANDLE hRecord);
  WINAPI_MSI_ERROR  MsiViewFetch(                   MSIHANDLE hView, MSIHANDLE* phRecord);
  MSIDBERROR        MsiViewGetError(                MSIHANDLE hView, LPTSTR szColumnNameBuffer, DWORD* pcchBuf);
  WINAPI_MSI_ERROR  MsiViewModify(                  MSIHANDLE hView, MSIMODIFY eModifyMode, MSIHANDLE hRecord);
  WINAPI_MSI_ERROR  MsiCreateTransformSummaryInfo(  MSIHANDLE hDatabase, MSIHANDLE hDatabaseReference, LPCTSTR szTransformFile, MSITRANSFORM_ERROR iErrorConditions, MSITRANSFORM_VALIDATE iValidation);
  WINAPI_MSI_ERROR  MsiDatabaseApplyTransform(      MSIHANDLE hDatabase, LPCTSTR szTransformFile, MSITRANSFORM_ERROR iErrorConditions);
  WINAPI_MSI_ERROR  MsiDatabaseExport(              MSIHANDLE hDatabase, LPCTSTR szTableName, LPCTSTR szFolderPath, LPCTSTR szFileName);
  WINAPI_MSI_ERROR  MsiDatabaseGenerateTransform(   MSIHANDLE hDatabase, MSIHANDLE hDatabaseReference, LPCTSTR szTransformFile, int iReserved1, int iReserved2);
  WINAPI_MSI_ERROR  MsiDatabaseImport(              MSIHANDLE hDatabase, LPCTSTR szFolderPath, LPCTSTR szFileName);
  WINAPI_MSI_ERROR  MsiDatabaseMerge(               MSIHANDLE hDatabase, MSIHANDLE hDatabaseMerge, LPCTSTR szTableName);
  MSIDBSTATE        MsiGetDatabaseState(            MSIHANDLE hDatabase);
  MSIHANDLE         MsiCreateRecord(                unsigned int cParams);
  WINAPI_MSI_ERROR  MsiFormatRecord(                MSIHANDLE hInstall, MSIHANDLE hRecord, LPTSTR szResultBuf, DWORD* pcchResultBuf);
  WINAPI_MSI_ERROR  MsiRecordClearData(             MSIHANDLE hRecord);
  WINAPI_MSI_ERROR  MsiRecordDataSize(              MSIHANDLE hRecord, unsigned int iField);
  WINAPI_MSI_ERROR  MsiRecordGetFieldCount(         MSIHANDLE hRecord);
  int               MsiRecordGetInteger(            MSIHANDLE hRecord, unsigned int iField);
  WINAPI_MSI_ERROR  MsiRecordGetString(             MSIHANDLE hRecord, unsigned int iField, LPTSTR szValueBuf, DWORD* pcchValueBuf);
  BOOL              MsiRecordIsNull(                MSIHANDLE hRecord, unsigned int iField);
  WINAPI_MSI_ERROR  MsiRecordReadStream(            MSIHANDLE hRecord, UINT iField, char* szDataBuf, DWORD* pcbDataBuf);
  WINAPI_MSI_ERROR  MsiRecordSetInteger(            MSIHANDLE hRecord, unsigned int iField, int iValue);
  WINAPI_MSI_ERROR  MsiRecordSetStream(             MSIHANDLE hRecord, UINT iField, LPCTSTR szFilePath);
  WINAPI_MSI_ERROR  MsiRecordSetString(             MSIHANDLE hRecord, unsigned int iField, LPCTSTR szValue);
  WINAPI_MSI_ERROR  MsiGetSummaryInformation(       MSIHANDLE hDatabase, LPCTSTR szDatabasePath, UINT uiUpdateCount, MSIHANDLE* phSummaryInfo);
  WINAPI_MSI_ERROR  MsiSummaryInfoGetProperty(      MSIHANDLE hSummaryInfo, WINAPI_MSI_PID uiProperty, WINAPI_MSI_DATA_TYPE* puiDataType, INT* piValue, FILETIME* pftValue, LPTSTR szValueBuf, DWORD* pcchValueBuf);
  WINAPI_MSI_ERROR  MsiSummaryInfoGetPropertyCount( MSIHANDLE hSummaryInfo, UINT* puiPropertyCount);
  WINAPI_MSI_ERROR  MsiSummaryInfoPersist(          MSIHANDLE hSummaryInfo);
  WINAPI_MSI_ERROR  MsiSummaryInfoSetProperty(      MSIHANDLE hSummaryInfo, WINAPI_MSI_PID uiProperty, WINAPI_MSI_DATA_TYPE uiDataType, INT iValue, FILETIME* pftValue, LPTSTR szValue);
  LANGID            MsiGetLanguage(                 MSIHANDLE hInstall);
  MSIHANDLE         MsiGetLastErrorRecord(          );
  BOOL              MsiGetMode(                     MSIHANDLE hInstall, MSIRUNMODE iRunMode);
  WINAPI_MSI_ERROR  MsiGetProperty(                 MSIHANDLE hInstall, LPCTSTR szName, LPTSTR szValueBuf, DWORD* pchValueBuf);
  WINAPI_MSI_ERROR  MsiSetProperty(                 MSIHANDLE hInstall, LPCTSTR szName, LPCTSTR szValue);
  WINAPI_MSI_ERROR  MsiSetMode(                     MSIHANDLE hInstall, unsigned int iRunMode, BOOL fState);
  WINAPI_MSI_ERROR  MsiDoAction(                    MSIHANDLE hInstall, LPCTSTR szAction);
  MSICONDITION      MsiEvaluateCondition(           MSIHANDLE hInstall, LPCTSTR szCondition);
  int               MsiProcessMessage(              MSIHANDLE hInstall, INSTALLMESSAGE eMessageType, MSIHANDLE hRecord);
  WINAPI_MSI_ERROR  MsiSequence(                    MSIHANDLE hInstall, LPCTSTR szTable, INT iSequenceMode);
  WINAPI_MSI_ERROR  MsiGetSourcePath(               MSIHANDLE hInstall, LPCTSTR szFolder, LPTSTR szPathBuf, DWORD* pcchPathBuf);
  WINAPI_MSI_ERROR  MsiGetTargetPath(               MSIHANDLE hInstall, LPCTSTR szFolder, LPTSTR szPathBuf, DWORD* pcchPathBuf);
  WINAPI_MSI_ERROR  MsiSetTargetPath(               MSIHANDLE hInstall, LPCTSTR szFolder, LPCTSTR szFolderPath);
  WINAPI_MSI_ERROR  MsiEnumComponentCosts(          MSIHANDLE hInstall, LPCTSTR szComponent, DWORD dwIndex, INSTALLSTATE iState, LPTSTR lpDriveBuf, DWORD* pcchDriveBuf, int* piCost, int* pTempCost);
  WINAPI_MSI_ERROR  MsiGetComponentState(           MSIHANDLE hInstall, LPCTSTR szComponent, INSTALLSTATE* piInstalled, INSTALLSTATE* piAction);
  WINAPI_MSI_ERROR  MsiGetFeatureCost(              MSIHANDLE hInstall, LPCTSTR szFeature, MSICOSTTREE iCostTree, INSTALLSTATE iState, INT* piCost);
  WINAPI_MSI_ERROR  MsiGetFeatureState(             MSIHANDLE hInstall, LPCTSTR szFeature, INSTALLSTATE* piInstalled, INSTALLSTATE* piAction);
  WINAPI_MSI_ERROR  MsiGetFeatureValidStates(       MSIHANDLE hInstall, LPCTSTR szFeature, WINAPI_INSTALLSTATE_DWORD* pInstallState);
  WINAPI_MSI_ERROR  MsiSetComponentState(           MSIHANDLE hInstall, LPCTSTR szComponent, INSTALLSTATE iState);
  WINAPI_MSI_ERROR  MsiSetFeatureAttributes(        MSIHANDLE hInstall, LPCTSTR szFeature, WINAPI_MsiInstallFeatureAttr dwAttributes);
  WINAPI_MSI_ERROR  MsiSetFeatureState(             MSIHANDLE hInstall, LPCTSTR szFeature, INSTALLSTATE iState);
  WINAPI_MSI_ERROR  MsiSetInstallLevel(             MSIHANDLE hInstall, int iInstallLevel);
  WINAPI_MSI_ERROR  MsiVerifyDiskSpace(             MSIHANDLE hInstall);
  WINAPI_MSI_ERROR  MsiEnableUIPreview(             MSIHANDLE hDatabase, MSIHANDLE* phPreview);
  WINAPI_MSI_ERROR  MsiPreviewBillboard(            MSIHANDLE hPreview, LPCTSTR szControlName, LPCTSTR szBillboard);
  WINAPI_MSI_ERROR  MsiPreviewDialog(               MSIHANDLE hPreview, LPCTSTR szDialogName);
]]
return ffi.load( 'Msi.dll' )
