require( 'ffi/winapi/headers/windows' )
require( 'ffi/winapi/headers/setup' )
require( 'ffi/winapi/headers/gdi' )
require( 'ffi/winapi/headers/registry' )
local ffi = require( 'ffi' )
ffi.cdef [[
  VOID         InstallHinfSection(                         HWND hwnd, HINSTANCE ModuleHandle, PCTSTR CmdLineBuffer, INT nCmdShow);
  BOOL         SetupAddInstallSectionToDiskSpaceList(      HDSKSPC DiskSpace, HINF InfHandle, HINF LayoutInfHandle, PCTSTR SectionName, PVOID Reserved1, UINT Reserved2);
  BOOL         SetupAddSectionToDiskSpaceList(             HDSKSPC DiskSpace, HINF InfHandle, HINF ListInfHandle, PCTSTR SectionName, UINT Operation, PVOID Reserved1, UINT Reserved2);
  BOOL         SetupAddToDiskSpaceList(                    HDSKSPC DiskSpace, PCTSTR TargetFilespec, LONGLONG FileSize, UINT Operation, PVOID Reserved1, UINT Reserved2);
  BOOL         SetupAddToSourceList(                       DWORD Flags, PCTSTR Source);
  BOOL         SetupAdjustDiskSpaceList(                   HDSKSPC DiskSpace, LPCTSTR DriveRoot, LONGLONG Amount, PVOID Reserved1, UINT Reserved2);
  UINT         SetupBackupError(                           HWND hwndParent, PCTSTR DialogTitle, PCTSTR SourceFile, PCTSTR TargetFile, UINT Win32ErrorCode, DWORD Style);
  BOOL         SetupCancelTemporarySourceList(             );
  void         SetupCloseFileQueue(                        HSPFILEQ QueueHandle);
  void         SetupCloseInfFile(                          HINF InfHandle);
  BOOL         SetupCommitFileQueue(                       HWND Owner, HSPFILEQ QueueHandle, PSP_FILE_CALLBACK MsgHandler, PVOID Context);
  BOOL         SetupConfigureWmiFromInfSection(            HINF InfHandle, PCWSTR SectionName, DWORD Flags);
  UINT         SetupCopyError(                             HWND hwndParent, PCTSTR DialogTitle, PCTSTR DiskName, PCTSTR PathToSource, PCTSTR SourceFile, PCTSTR TargetPathFile, UINT Win32ErrorCode, DWORD Style, PTSTR PathBuffer, DWORD PathBufferSize, PDWORD PathRequiredSize);
  BOOL         SetupCopyOEMInf(                            PCTSTR SourceInfFileName, PCTSTR OEMSourceMediaLocation, DWORD OEMSourceMediaType, DWORD CopyStyle, PTSTR DestinationInfFileName, DWORD DestinationInfFileNameSize, PDWORD RequiredSize, PTSTR DestinationInfFileNameComponent);
  HDSKSPC      SetupCreateDiskSpaceList(                   PVOID Reserved1, DWORD Reserved2, WINAPI_SPDSL_FLAGS Flags);
  DWORD        SetupDecompressOrCopyFile(                  PCTSTR SourceFileName, PCTSTR TargetFileName, PUINT CompressionType);
  UINT         SetupDefaultQueueCallback(                  PVOID Context, UINT Notification, UINT Param1, UINT Param2);
  UINT         SetupDeleteError(                           HWND hwndParent, PCTSTR DialogTitle, PCTSTR File, UINT Win32ErrorCode, DWORD Style);
  BOOL         SetupDestroyDiskSpaceList(                  HDSKSPC DiskSpace);
  HDSKSPC      SetupDuplicateDiskSpaceList(                HDSKSPC DiskSpace, PVOID Reserved1, DWORD Reserved2, UINT Flags);
  BOOL         SetupEnumInfSections(                       HINF InfHandle, UINT EnumerationIndex, PTSTR ReturnBuffer, DWORD ReturnBufferSize, PDWORD RequiredSize);
  BOOL         SetupFindFirstLine(                         HINF InfHandle, PCTSTR Section, PCTSTR Key, PINFCONTEXT Context);
  BOOL         SetupFindNextLine(                          PINFCONTEXT ContextIn, PINFCONTEXT ContextOut);
  BOOL         SetupFindNextMatchLine(                     PINFCONTEXT ContextIn, PCTSTR Key, PINFCONTEXT ContextOut);
  BOOL         SetupFreeSourceList(                        PCTSTR** List, UINT Count);
  BOOL         SetupGetBinaryField(                        PINFCONTEXT Context, DWORD FieldIndex, BYTE* ReturnBuffer, DWORD ReturnBufferSize, LPDWORD RequiredSize);
  DWORD        SetupGetFieldCount(                         PINFCONTEXT Context);
  DWORD        SetupGetFileCompressionInfo(                PCTSTR SourceFileName, PTSTR* ActualSourceFileName, PDWORD SourceFileSize, PDWORD TargetFileSize, PUINT CompressionType);
  BOOL         SetupGetFileCompressionInfoEx(              PCTSTR SourceFileName, PTSTR ActualSourceFileNameBuffer, DWORD ActualSourceFileNameLen, PDWORD RequiredBufferLen, PDWORD SourceFileSize, PDWORD TargetFileSize, PUINT CompressionType);
  BOOL         SetupGetFileQueueCount(                     HSPFILEQ FileQueue, UINT SubQueueFileOp, PUINT NumOperations);
  BOOL         SetupGetFileQueueFlags(                     HSPFILEQ FileQueue, PDWORD Flags);
  BOOL         SetupGetInfFileList(                        PCTSTR DirectoryPath, WINAPI_InfStyle InfStyle, PTSTR ReturnBuffer, DWORD ReturnBufferSize, PDWORD RequiredSize);
  BOOL         SetupGetInfInformation(                     LPCVOID InfSpec, DWORD SearchControl, PSP_INF_INFORMATION ReturnBuffer, DWORD ReturnBufferSize, PDWORD RequiredSize);
  BOOL         SetupGetIntField(                           PINFCONTEXT Context, DWORD FieldIndex, PINT IntegerValue);
  BOOL         SetupGetLineByIndex(                        HINF InfHandle, PCTSTR Section, DWORD Index, PINFCONTEXT Context);
  LONG         SetupGetLineCount(                          HINF InfHandle, PCTSTR Section);
  BOOL         SetupGetLineText(                           PINFCONTEXT Context, HINF InfHandle, PCTSTR Section, PCTSTR Key, PTSTR ReturnBuffer, DWORD ReturnBufferSize, PDWORD RequiredSize);
  BOOL         SetupGetMultiSzField(                       PINFCONTEXT Context, DWORD FieldIndex, PTSTR ReturnBuffer, DWORD ReturnBufferSize, LPDWORD RequiredSize);
  BOOL         SetupGetSourceFileLocation(                 HINF InfHandle, PINFCONTEXT InfContext, PCTSTR FileName, PUINT SourceId, PTSTR ReturnBuffer, DWORD ReturnBufferSize, PDWORD RequiredSize);
  BOOL         SetupGetSourceFileSize(                     HINF InfHandle, PINFCONTEXT InfContext, PCTSTR FileName, PCTSTR Section, PDWORD FileSize, UINT RoundingFactor);
  BOOL         SetupGetSourceInfo(                         HINF InfHandle, UINT SourceId, UINT InfoDesired, PTSTR ReturnBuffer, DWORD ReturnBufferSize, LPDWORD RequiredSize);
  BOOL         SetupGetStringField(                        PINFCONTEXT Context, DWORD FieldIndex, PTSTR ReturnBuffer, DWORD ReturnBufferSize, PDWORD RequiredSize);
  BOOL         SetupGetTargetPath(                         HINF InfHandle, PINFCONTEXT InfContext, PCTSTR Section, PTSTR ReturnBuffer, DWORD ReturnBufferSize, PDWORD RequiredSize);
  PVOID        SetupInitDefaultQueueCallback(              HWND OwnerWindow);
  PVOID        SetupInitDefaultQueueCallbackEx(            HWND OwnerWindow, HWND AlternateProgressWindow, UINT ProgressMessage, DWORD Reserved1, PVOID Reserved2);
  HSPFILELOG   SetupInitializeFileLog(                     PCTSTR LogFileName, DWORD Flags);
  BOOL         SetupInstallFile(                           HINF InfHandle, PINFCONTEXT InfContext, PCTSTR SourceFile, PCTSTR SourcePathRoot, PCTSTR DestinationName, DWORD CopyStyle, PSP_FILE_CALLBACK CopyMsgHandler, PVOID Context);
  BOOL         SetupInstallFileEx(                         HINF InfHandle, PINFCONTEXT InfContext, PCTSTR SourceFile, PCTSTR SourcePathRoot, PCTSTR DestinationName, DWORD CopyStyle, PSP_FILE_CALLBACK CopyMsgHandler, PVOID Context, PBOOL FileWasInUse);
  BOOL         SetupInstallFilesFromInfSection(            HINF InfHandle, HINF LayoutInfHandle, HSPFILEQ FileQueue, PCTSTR SectionName, PCTSTR SourceRootPath, UINT CopyFlags);
  BOOL         SetupInstallFromInfSection(                 HWND Owner, HINF InfHandle, PCTSTR SectionName, WINAPI_SPINST_FLAGS Flags, HKEY RelativeKeyRoot, PCTSTR SourceRootPath, UINT CopyFlags, PSP_FILE_CALLBACK MsgHandler, PVOID Context, HDEVINFO DeviceInfoSet, PSP_DEVINFO_DATA DeviceInfoData);
  BOOL         SetupInstallServicesFromInfSection(         HINF InfHandle, PCTSTR SectionName, DWORD Flags);
  BOOL         SetupInstallServicesFromInfSectionEx(       HINF InfHandle, PCTSTR SectionName, DWORD Flags, HDEVINFO DeviceInfoSet, PSP_DEVINFO_DATA DeviceInfoData, PVOID Reserved1, PVOID Reserved2);
  BOOL         SetupIterateCabinet(                        PCTSTR CabinetFile, DWORD Reserved, PSP_FILE_CALLBACK MsgHandler, PVOID Context);
  BOOL         SetupLogFile(                               HSPFILELOG FileLogHandle, PCTSTR LogSectionName, PCTSTR SourceFileName, PCTSTR TargetFileName, DWORD Checksum, PCTSTR DiskTagfile, PCTSTR DiskDescription, PCTSTR OtherInfo, DWORD Flags);
  BOOL         SetupLogError(                              PCTSTR MessageString, LogSeverity Severity);
  BOOL         SetupOpenAppendInfFile(                     PCTSTR FileName, HINF InfHandle, PUINT ErrorLine);
  HSPFILEQ     SetupOpenFileQueue(                         );
  HINF         SetupOpenInfFile(                           PCTSTR FileName, PCTSTR InfClass, WINAPI_InfStyle InfStyle, PUINT ErrorLine);
  HINF         SetupOpenMasterInf(                         );
  UINT         SetupPromptForDisk(                         HWND hwndParent, PCTSTR DialogTitle, PCTSTR DiskName, PCTSTR PathToSource, PCTSTR FileSought, PCTSTR TagFile, DWORD DiskPromptStyle, PTSTR PathBuffer, DWORD PathBufferSize, PDWORD PathRequiredSize);
  INT          SetupPromptReboot(                          HSPFILEQ FileQueue, HWND Owner, BOOL ScanOnly);
  BOOL         SetupQueryDrivesInDiskSpaceList(            HDSKSPC DiskSpace, PSTR ReturnBuffer, DWORD ReturnBufferSize, PDWORD RequiredSize);
  BOOL         SetupQueryFileLog(                          HSPFILELOG FileLogHandle, PCTSTR LogSectionName, PCTSTR TargetFileName, SetupFileLogInfo DesiredInfo, PTSTR DataOut, DWORD ReturnBufferSize, PDWORD RequiredSize);
  BOOL         SetupQueryInfFileInformation(               PSP_INF_INFORMATION InfInformation, UINT InfIndex, PTSTR ReturnBuffer, DWORD ReturnBufferSize, PDWORD RequiredSize);
  BOOL         SetupQueryInfOriginalFileInformation(       PSP_INF_INFORMATION InfInformation, UINT InfIndex, PSP_ALTPLATFORM_INFO AlternatePlatformInfo, PSP_ORIGINAL_FILE_INFO OriginalFileInfo);
  BOOL         SetupQueryInfVersionInformation(            PSP_INF_INFORMATION InfInformation, UINT InfIndex, PCTSTR Key, PTSTR ReturnBuffer, DWORD ReturnBufferSize, PDWORD RequiredSize);
  BOOL         SetupQuerySourceList(                       DWORD Flags, PCTSTR** List, PUINT Count);
  BOOL         SetupQuerySpaceRequiredOnDrive(             HDSKSPC DiskSpace, PCTSTR DriveSpec, LONGLONG* SpaceRequired, PVOID Reserved1, UINT Reserved2);
  BOOL         SetupQueueCopy(                             HSPFILEQ QueueHandle, PCTSTR SourceRootPath, PCTSTR SourcePath, PCTSTR SourceFileName, PCTSTR SourceDescription, PCTSTR SourceTagFile, PCTSTR TargetDirectory, PCTSTR TargetFileName, DWORD CopyStyle);
  BOOL         SetupQueueCopyIndirect(                     PSP_FILE_COPY_PARAMS CopyParams);
  BOOL         SetupQueueCopySection(                      HSPFILEQ QueueHandle, PCTSTR SourceRootPath, HINF InfHandle, HINF ListInfHandle, PCTSTR Section, DWORD CopyStyle);
  BOOL         SetupQueueDefaultCopy(                      HSPFILEQ QueueHandle, HINF InfHandle, PCTSTR SourceRootPath, PCTSTR SourceFileName, PCTSTR TargetFileName, DWORD CopyStyle);
  BOOL         SetupQueueDelete(                           HSPFILEQ QueueHandle, PCTSTR PathPart1, PCTSTR PathPart2);
  BOOL         SetupQueueDeleteSection(                    HSPFILEQ QueueHandle, HINF InfHandle, HINF ListInfHandle, PCTSTR Section);
  BOOL         SetupQueueRename(                           HSPFILEQ QueueHandle, PCTSTR SourcePath, PCTSTR SourceFileName, PCTSTR TargetPath, PCTSTR TargetFileName);
  BOOL         SetupQueueRenameSection(                    HSPFILEQ QueueHandle, HINF InfHandle, HINF ListInfHandle, PCTSTR Section);
  BOOL         SetupRemoveFileLogEntry(                    HSPFILELOG FileLogHandle, PCTSTR LogSectionName, PCTSTR TargetFileName);
  BOOL         SetupRemoveFromDiskSpaceList(               HDSKSPC DiskSpace, PCTSTR TargetFilespec, UINT Operation, PVOID Reserved1, UINT Reserved2);
  BOOL         SetupRemoveFromSourceList(                  DWORD Flags, PCTSTR Source);
  BOOL         SetupRemoveInstallSectionFromDiskSpaceList( HDSKSPC DiskSpace, HINF InfHandle, HINF LayoutInfHandle, PCTSTR SectionName, PVOID Reserved1, UINT Reserved2);
  BOOL         SetupRemoveSectionFromDiskSpaceList(        HDSKSPC DiskSpace, HINF InfHandle, HINF ListInfHandle, PCTSTR SectionName, UINT Operation, PVOID Reserved1, UINT Reserved2);
  UINT         SetupRenameError(                           HWND hwndParent, PCTSTR DialogTitle, PCTSTR SourceFile, PCTSTR TargetFile, UINT Win32ErrorCode, DWORD Style);
  BOOL         SetupScanFileQueue(                         HSPFILEQ FileQueue, DWORD Flags, HWND Window, PSP_FILE_CALLBACK CallbackRoutine, PVOID CallbackContext, PDWORD Result);
  BOOL         SetupSetDirectoryId(                        HINF InfHandle, DWORD Id, PCTSTR Directory);
  BOOL         SetupSetDirectoryIdEx(                      HINF InfHandle, DWORD Id, PCTSTR Directory, DWORD Flags, DWORD Reserved1, PVOID Reserved2);
  BOOL         SetupSetFileQueueAlternatePlatform(         HSPFILEQ QueueHandle, PSP_ALTPLATFORM_INFO AlternatePlatformInfo, PCWSTR AlternateDefaultCatalogFile);
  BOOL         SetupSetFileQueueFlags(                     HSPFILEQ FileQueue, DWORD FlagMask, DWORD Flags);
  BOOL         SetupSetPlatformPathOverride(               PCTSTR Override);
  BOOL         SetupSetSourceList(                         DWORD Flags, PCTSTR* SourceList, UINT SourceCount);
  void         SetupTermDefaultQueueCallback(              PVOID Context);
  BOOL         SetupTerminateFileLog(                      HSPFILELOG FileLogHandle);
  BOOL         SetupUninstallNewlyCopiedInfs(              HSPFILEQ QueueHandle, DWORD Flags, PVOID Reserved);
  BOOL         SetupUninstallOEMInf(                       PCWSTR InfFileName, DWORD Flags, PVOID Reserved);
  BOOL         SetupVerifyInfFile(                         PCWSTR InfName, PSP_ALTPLATFORM_INFO AltPlatformInfo, PSP_INF_SIGNER_INFO InfFileName);
  BOOL         SetupGetInfDriverStoreLocation(             PCTSTR FileName, PSP_ALTPLATFORM_INFO AlternatePlatformInfo, PCTSTR LocaleName, PTSTR ReturnBuffer, DWORD ReturnBufferSize, PDWORD RequiredSize);
  BOOL         SetupGetInfPublishedName(                   PCTSTR DriverStoreLocation, PTSTR ReturnBuffer, DWORD ReturnBufferSize, PDWORD RequiredSize);
  BOOL         SetupGetNonInteractiveMode(                 );
  BOOL         SetupSetNonInteractiveMode(                 BOOL NonInteractiveFlag);
  BOOL         SetupDiAskForOEMDisk(                       HDEVINFO DeviceInfoSet, PSP_DEVINFO_DATA DeviceInfoData);
  BOOL         SetupDiBuildClassInfoList(                  WINAPI_SetupDiBuildClassInfoListFlags Flags, LPGUID ClassGuidList, DWORD ClassGuidListSize, PDWORD RequiredSize);
  BOOL         SetupDiBuildClassInfoListEx(                WINAPI_SetupDiBuildClassInfoListFlags Flags, LPGUID ClassGuidList, DWORD ClassGuidListSize, PDWORD RequiredSize, PCTSTR MachineName, PVOID Reserved);
  BOOL         SetupDiBuildDriverInfoList(                 HDEVINFO DeviceInfoSet, PSP_DEVINFO_DATA DeviceInfoData, WINAPI_DiDriverType DriverType);
  BOOL         SetupDiCallClassInstaller(                  DI_FUNCTION InstallFunction, HDEVINFO DeviceInfoSet, PSP_DEVINFO_DATA DeviceInfoData);
  BOOL         SetupDiCancelDriverInfoSearch(              HDEVINFO DeviceInfoSet);
  BOOL         SetupDiChangeState(                         HDEVINFO DeviceInfoSet, PSP_DEVINFO_DATA DeviceInfoData);
  BOOL         SetupDiClassGuidsFromName(                  PCTSTR ClassName, LPGUID ClassGuidList, DWORD ClassGuidListSize, PDWORD RequiredSize);
  BOOL         SetupDiClassGuidsFromNameEx(                PCTSTR ClassName, LPGUID ClassGuidList, DWORD ClassGuidListSize, PDWORD RequiredSize, PCTSTR MachineName, PVOID Reserved);
  BOOL         SetupDiClassNameFromGuid(                   LPGUID ClassGuid, PTSTR ClassName, DWORD ClassNameSize, PDWORD RequiredSize);
  BOOL         SetupDiClassNameFromGuidEx(                 LPGUID ClassGuid, PTSTR ClassName, DWORD ClassNameSize, PDWORD RequiredSize, PCTSTR MachineName, PVOID Reserved);
  BOOL         SetupDiCreateDeviceInfo(                    HDEVINFO DeviceInfoSet, PCTSTR DeviceName, LPGUID ClassGuid, PCTSTR DeviceDescription, HWND hwndParent, WINAPI_SetupDiCreateDeviceInfoFlags CreationFlags, PSP_DEVINFO_DATA DeviceInfoData);
  HDEVINFO     SetupDiCreateDeviceInfoList(                LPGUID ClassGuid, HWND hwndParent);
  HDEVINFO     SetupDiCreateDeviceInfoListEx(              LPGUID ClassGuid, HWND hwndParent, PCTSTR MachineName, PVOID Reserved);
  BOOL         SetupDiCreateDeviceInterface(               HDEVINFO DeviceInfoSet, PSP_DEVINFO_DATA DeviceInfoData, LPGUID InterfaceClassGuid, PCTSTR ReferenceString, DWORD CreationFlags, PSP_DEVICE_INTERFACE_DATA DeviceInterfaceData);
  HKEY         SetupDiCreateDeviceInterfaceRegKey(         HDEVINFO DeviceInfoSet, PSP_DEVICE_INTERFACE_DATA DeviceInterfaceData, DWORD Reserved, REGSAM samDesired, HINF InfHandle, PCTSTR InfSectionName);
  HKEY         SetupDiCreateDevRegKey(                     HDEVINFO DeviceInfoSet, PSP_DEVINFO_DATA DeviceInfoData, WINAPI_DeviceInfoScope Scope, DWORD HwProfile, WINAPI_DeviceInfoKeyType KeyType, HINF InfHandle, PCTSTR InfSectionName);
  BOOL         SetupDiDeleteDeviceInfo(                    HDEVINFO DeviceInfoSet, PSP_DEVINFO_DATA DeviceInfoData);
  BOOL         SetupDiDeleteDeviceInterfaceData(           HDEVINFO DeviceInfoSet, PSP_DEVICE_INTERFACE_DATA DeviceInterfaceData);
  BOOL         SetupDiDeleteDeviceInterfaceRegKey(         HDEVINFO DeviceInfoSet, PSP_DEVICE_INTERFACE_DATA DeviceInterfaceData, DWORD Reserved);
  BOOL         SetupDiDeleteDevRegKey(                     HDEVINFO DeviceInfoSet, PSP_DEVINFO_DATA DeviceInfoData, WINAPI_DeviceInfoScope Scope, DWORD HwProfile, WINAPI_DeviceInfoKeyType KeyType);
  BOOL         SetupDiDestroyClassImageList(               PSP_CLASSIMAGELIST_DATA ClassImageListData);
  BOOL         SetupDiDestroyDeviceInfoList(               HDEVINFO DeviceInfoSet);
  BOOL         SetupDiDestroyDriverInfoList(               HDEVINFO DeviceInfoSet, PSP_DEVINFO_DATA DeviceInfoData, WINAPI_DiDriverType DriverType);
  INT          SetupDiDrawMiniIcon(                        HDC hdc, RECT rc, INT MiniIconIndex, DWORD Flags);
  BOOL         SetupDiEnumDeviceInfo(                      HDEVINFO DeviceInfoSet, DWORD MemberIndex, PSP_DEVINFO_DATA DeviceInfoData);
  BOOL         SetupDiEnumDeviceInterfaces(                HDEVINFO DeviceInfoSet, PSP_DEVINFO_DATA DeviceInfoData, LPGUID InterfaceClassGuid, DWORD MemberIndex, PSP_DEVICE_INTERFACE_DATA DeviceInterfaceData);
  BOOL         SetupDiEnumDriverInfo(                      HDEVINFO DeviceInfoSet, PSP_DEVINFO_DATA DeviceInfoData, WINAPI_DiDriverType DriverType, DWORD MemberIndex, PSP_DRVINFO_DATA DriverInfoData);
  BOOL         SetupDiGetActualModelsSection(              PINFCONTEXT Context, PSP_ALTPLATFORM_INFO AlternatePlatformInfo, PTSTR DecoratedModelsSection, DWORD DecoratedModelsSectionSize, PDWORD RequiredSize, PVOID Reserved);
  BOOL         SetupDiGetActualSectionToInstall(           HINF InfHandle, PCTSTR InfSectionName, PTSTR InfSectionWithExt, DWORD InfSectionWithExtSize, PDWORD RequiredSize, PTSTR* Extension);
  BOOL         SetupDiGetActualSectionToInstallEx(         HINF InfHandle, PCTSTR InfSectionName, PSP_ALTPLATFORM_INFO AlternatePlatformInfo, PTSTR InfSectionWithExt, DWORD InfSectionWithExtSize, PDWORD RequiredSize, PTSTR* Extension, PVOID Reserved);
  BOOL         SetupDiGetClassBitmapIndex(                 LPGUID ClassGuid, PINT MiniIconIndex);
  BOOL         SetupDiGetClassDescription(                 LPGUID ClassGuid, PTSTR ClassDescription, DWORD ClassDescriptionSize, PDWORD RequiredSize);
  BOOL         SetupDiGetClassDescriptionEx(               LPGUID ClassGuid, PTSTR ClassDescription, DWORD ClassDescriptionSize, PDWORD RequiredSize, PCTSTR MachineName, PVOID Reserved);
  BOOL         SetupDiGetClassDevPropertySheets(           HDEVINFO DeviceInfoSet, PSP_DEVINFO_DATA DeviceInfoData, LPPROPSHEETHEADER PropertySheetHeader, DWORD PropertySheetHeaderPageListSize, PDWORD RequiredSize, WINAPI_DiGetClassDevPropertySheetsType PropertySheetType);
  HDEVINFO     SetupDiGetClassDevs(                        LPGUID ClassGuid, PCTSTR Enumerator, HWND hwndParent, WINAPI_DeviceInfoGetFlags Flags);
  HDEVINFO     SetupDiGetClassDevsEx(                      LPGUID ClassGuid, PCTSTR Enumerator, HWND hwndParent, WINAPI_DeviceInfoGetFlags Flags, HDEVINFO DeviceInfoSet, PCTSTR MachineName, PVOID Reserved);
  BOOL         SetupDiGetClassImageIndex(                  PSP_CLASSIMAGELIST_DATA ClassImageListData, LPGUID ClassGuid, PINT ImageIndex);
  BOOL         SetupDiGetClassImageList(                   PSP_CLASSIMAGELIST_DATA ClassImageListData);
  BOOL         SetupDiGetClassImageListEx(                 PSP_CLASSIMAGELIST_DATA ClassImageListData, PCTSTR MachineName, PVOID Reserved);
  BOOL         SetupDiGetClassInstallParams(               HDEVINFO DeviceInfoSet, PSP_DEVINFO_DATA DeviceInfoData, PSP_CLASSINSTALL_HEADER ClassInstallParams, DWORD ClassInstallParamsSize, PDWORD RequiredSize);
  BOOL         SetupDiGetClassPropertyW(                   WINAPI_GUID* ClassGuid, WINAPI_DEVPROPKEY* PropertyKey, DEVPROPTYPE* PropertyType, PBYTE PropertyBuffer, DWORD PropertyBufferSize, PDWORD RequiredSize, WINAPI_DiClassPropertyFlags Flags);
  BOOL         SetupDiGetClassPropertyExW(                 WINAPI_GUID* ClassGuid, WINAPI_DEVPROPKEY* PropertyKey, DEVPROPTYPE* PropertyType, PBYTE PropertyBuffer, DWORD PropertyBufferSize, PDWORD RequiredSize, WINAPI_DiClassPropertyFlags Flags, PCWSTR MachineName, PVOID Reserved);
  BOOL         SetupDiGetClassPropertyKeys(                WINAPI_GUID* ClassGuid, DEVPROPKEY* PropertyKeyArray, DWORD PropertyKeyCount, PDWORD RequiredPropertyKeyCount, WINAPI_DiClassPropertyFlags Flags);
  BOOL         SetupDiGetClassPropertyKeysExW(             WINAPI_GUID* ClassGuid, DEVPROPKEY* PropertyKeyArray, DWORD PropertyKeyCount, PDWORD RequiredPropertyKeyCount, WINAPI_DiClassPropertyFlags Flags, PCWSTR MachineName, PVOID Reserved);
  BOOL         SetupDiGetClassRegistryProperty(            LPGUID ClassGuid, DWORD Property, WINAPI_RegType* PropertyRegDataType, PBYTE PropertyBuffer, DWORD PropertyBufferSize, PDWORD RequiredSize, PCTSTR MachineName, PVOID Reserved);
  BOOL         SetupDiGetCustomDeviceProperty(             HDEVINFO DeviceInfoSet, PSP_DEVINFO_DATA DeviceInfoData, PCTSTR CustomPropertyName, WINAPI_GetCustomDevicePropertyFlags Flags, WINAPI_RegType* PropertyRegDataType, PBYTE PropertyBuffer, DWORD PropertyBufferSize, PDWORD RequiredSize);
  BOOL         SetupDiGetDeviceInfoListClass(              HDEVINFO DeviceInfoSet, LPGUID ClassGuid);
  BOOL         SetupDiGetDeviceInfoListDetail(             HDEVINFO DeviceInfoSet, PSP_DEVINFO_LIST_DETAIL_DATA DeviceInfoSetDetailData);
  BOOL         SetupDiGetDeviceInstallParams(              HDEVINFO DeviceInfoSet, PSP_DEVINFO_DATA DeviceInfoData, PSP_DEVINSTALL_PARAMS DeviceInstallParams);
  BOOL         SetupDiGetDeviceInstanceId(                 HDEVINFO DeviceInfoSet, PSP_DEVINFO_DATA DeviceInfoData, PTSTR DeviceInstanceId, DWORD DeviceInstanceIdSize, PDWORD RequiredSize);
  BOOL         SetupDiGetDeviceInterfaceAlias(             HDEVINFO DeviceInfoSet, PSP_DEVICE_INTERFACE_DATA DeviceInterfaceData, LPGUID AliasInterfaceClassGuid, PSP_DEVICE_INTERFACE_DATA AliasDeviceInterfaceData);
  BOOL         SetupDiGetDeviceInterfaceDetail(            HDEVINFO DeviceInfoSet, PSP_DEVICE_INTERFACE_DATA DeviceInterfaceData, PSP_DEVICE_INTERFACE_DETAIL_DATA DeviceInterfaceDetailData, DWORD DeviceInterfaceDetailDataSize, PDWORD RequiredSize, PSP_DEVINFO_DATA DeviceInfoData);
  BOOL         SetupDiGetDeviceInterfacePropertyW(         HDEVINFO DeviceInfoSet, PSP_DEVICE_INTERFACE_DATA DeviceInterfaceData, WINAPI_DEVPROPKEY* PropertyKey, DEVPROPTYPE* PropertyType, PBYTE PropertyBuffer, DWORD PropertyBufferSize, PDWORD RequiredSize, DWORD Flags);
  BOOL         SetupDiGetDeviceInterfacePropertyKeys(      HDEVINFO DeviceInfoSet, PSP_DEVICE_INTERFACE_DATA DeviceInterfaceData, DEVPROPKEY* PropertyKeyArray, DWORD PropertyKeyCount, PDWORD RequiredPropertyKeyCount, DWORD Flags);
  BOOL         SetupDiGetDevicePropertyW(                  HDEVINFO DeviceInfoSet, PSP_DEVINFO_DATA DeviceInfoData, WINAPI_DEVPROPKEY* PropertyKey, DEVPROPTYPE* PropertyType, PBYTE PropertyBuffer, DWORD PropertyBufferSize, PDWORD RequiredSize, DWORD Flags);
  BOOL         SetupDiGetDevicePropertyKeys(               HDEVINFO DeviceInfoSet, PSP_DEVINFO_DATA DeviceInfoData, DEVPROPKEY* PropertyKeyArray, DWORD PropertyKeyCount, PDWORD RequiredPropertyKeyCount, DWORD Flags);
  BOOL         SetupDiGetDeviceRegistryProperty(           HDEVINFO DeviceInfoSet, PSP_DEVINFO_DATA DeviceInfoData, WINAPI_SetupDeviceRegistryProperty Property, WINAPI_RegType* PropertyRegDataType, PBYTE PropertyBuffer, DWORD PropertyBufferSize, PDWORD RequiredSize);
  BOOL         SetupDiGetDriverInfoDetail(                 HDEVINFO DeviceInfoSet, PSP_DEVINFO_DATA DeviceInfoData, PSP_DRVINFO_DATA DriverInfoData, PSP_DRVINFO_DETAIL_DATA DriverInfoDetailData, DWORD DriverInfoDetailDataSize, PDWORD RequiredSize);
  BOOL         SetupDiGetDriverInstallParams(              HDEVINFO DeviceInfoSet, PSP_DEVINFO_DATA DeviceInfoData, PSP_DRVINFO_DATA DriverInfoData, PSP_DRVINSTALL_PARAMS DriverInstallParams);
  BOOL         SetupDiGetHwProfileFriendlyName(            DWORD HwProfile, PTSTR FriendlyName, DWORD FriendlyNameSize, PDWORD RequiredSize);
  BOOL         SetupDiGetHwProfileFriendlyNameEx(          DWORD HwProfile, PTSTR FriendlyName, DWORD FriendlyNameSize, PDWORD RequiredSize, PCTSTR MachineName, PVOID Reserved);
  BOOL         SetupDiGetHwProfileList(                    PDWORD HwProfileList, DWORD HwProfileListSize, PDWORD RequiredSize, PDWORD CurrentlyActiveIndex);
  BOOL         SetupDiGetHwProfileListEx(                  PDWORD HwProfileList, DWORD HwProfileListSize, PDWORD RequiredSize, PDWORD CurrentlyActiveIndex, PCTSTR MachineName, PVOID Reserved);
  BOOL         SetupDiGetINFClass(                         PCTSTR InfName, LPGUID ClassGuid, PTSTR ClassName, DWORD ClassNameSize, PDWORD RequiredSize);
  BOOL         SetupDiGetSelectedDevice(                   HDEVINFO DeviceInfoSet, PSP_DEVINFO_DATA DeviceInfoData);
  BOOL         SetupDiGetSelectedDriver(                   HDEVINFO DeviceInfoSet, PSP_DEVINFO_DATA DeviceInfoData, PSP_DRVINFO_DATA DriverInfoData);
  BOOL         SetupDiInstallClass(                        HWND hwndParent, PCTSTR InfFileName, DWORD Flags, HSPFILEQ FileQueue);
  BOOL         SetupDiInstallClassEx(                      HWND hwndParent, PCTSTR InfFileName, DWORD Flags, HSPFILEQ FileQueue, LPGUID InterfaceClassGuid, PVOID Reserved1, PVOID Reserved2);
  BOOL         SetupDiInstallDevice(                       HDEVINFO DeviceInfoSet, PSP_DEVINFO_DATA DeviceInfoData);
  BOOL         SetupDiInstallDeviceInterfaces(             HDEVINFO DeviceInfoSet, PSP_DEVINFO_DATA DeviceInfoData);
  BOOL         SetupDiInstallDriverFiles(                  HDEVINFO DeviceInfoSet, PSP_DEVINFO_DATA DeviceInfoData);
  BOOL         SetupDiLoadClassIcon(                       LPGUID ClassGuid, HICON* LargeIcon, LPINT MiniIconIndex);
  BOOL         SetupDiLoadDeviceIcon(                      HDEVINFO DeviceInfoSet, PSP_DEVINFO_DATA DeviceInfoData, UINT cxIcon, UINT cyIcon, DWORD Flags, HICON* hIcon);
  HKEY         SetupDiOpenClassRegKey(                     LPGUID ClassGuid, REGSAM samDesired);
  HKEY         SetupDiOpenClassRegKeyEx(                   LPGUID ClassGuid, REGSAM samDesired, DWORD Flags, PCTSTR MachineName, PVOID Reserved);
  BOOL         SetupDiOpenDeviceInfo(                      HDEVINFO DeviceInfoSet, PCTSTR DeviceInstanceId, HWND hwndParent, WINAPI_OpenDeviceInfoFlags OpenFlags, PSP_DEVINFO_DATA DeviceInfoData);
  BOOL         SetupDiOpenDeviceInterface(                 HDEVINFO DeviceInfoSet, PCTSTR DevicePath, WINAPI_OpenDeviceInterfaceFlags OpenFlags, PSP_DEVICE_INTERFACE_DATA DeviceInterfaceData);
  HKEY         SetupDiOpenDeviceInterfaceRegKey(           HDEVINFO DeviceInfoSet, PSP_DEVICE_INTERFACE_DATA DeviceInterfaceData, DWORD Reserved, REGSAM samDesired);
  HKEY         SetupDiOpenDevRegKey(                       HDEVINFO DeviceInfoSet, PSP_DEVINFO_DATA DeviceInfoData, WINAPI_DeviceInfoScope Scope, DWORD HwProfile, WINAPI_DeviceInfoKeyType KeyType, REGSAM samDesired);
  BOOL         SetupDiRegisterCoDeviceInstallers(          HDEVINFO DeviceInfoSet, PSP_DEVINFO_DATA DeviceInfoData);
  BOOL         SetupDiRegisterDeviceInfo(                  HDEVINFO DeviceInfoSet, PSP_DEVINFO_DATA DeviceInfoData, DWORD Flags, PSP_DETSIG_CMPPROC CompareProc, PVOID CompareContext, PSP_DEVINFO_DATA DupDeviceInfoData);
  BOOL         SetupDiRemoveDevice(                        HDEVINFO DeviceInfoSet, PSP_DEVINFO_DATA DeviceInfoData);
  BOOL         SetupDiRemoveDeviceInterface(               HDEVINFO DeviceInfoSet, PSP_DEVICE_INTERFACE_DATA DeviceInterfaceData);
  BOOL         SetupDiRestartDevices(                      HDEVINFO DeviceInfoSet, PSP_DEVINFO_DATA DeviceInfoData);
  BOOL         SetupDiSelectBestCompatDrv(                 HDEVINFO DeviceInfoSet, PSP_DEVINFO_DATA DeviceInfoData);
  BOOL         SetupDiSelectDevice(                        HDEVINFO DeviceInfoSet, PSP_DEVINFO_DATA DeviceInfoData);
  BOOL         SetupDiSelectOEMDrv(                        HWND hwndParent, HDEVINFO DeviceInfoSet, PSP_DEVINFO_DATA DeviceInfoData);
  BOOL         SetupDiSetClassInstallParams(               HDEVINFO DeviceInfoSet, PSP_DEVINFO_DATA DeviceInfoData, PSP_CLASSINSTALL_HEADER ClassInstallParams, DWORD ClassInstallParamsSize);
  BOOL         SetupDiSetClassPropertyW(                   WINAPI_GUID* ClassGuid, WINAPI_DEVPROPKEY* PropertyKey, DEVPROPTYPE PropertyType, WINAPI_PBYTE PropertyBuffer, DWORD PropertyBufferSize, WINAPI_DiClassPropertyFlags Flags);
  BOOL         SetupDiSetClassPropertyExW(                 WINAPI_GUID* ClassGuid, WINAPI_DEVPROPKEY* PropertyKey, DEVPROPTYPE PropertyType, WINAPI_BYTE PropertyBuffer, DWORD PropertyBufferSize, DWORD Flags, PVOID Reserved);
  BOOL         SetupDiSetClassRegistryProperty(            LPGUID ClassGuid, DWORD Property, WINAPI_BYTE* PropertyBuffer, DWORD PropertyBufferSize, PCTSTR MachineName, PVOID Reserved);
  BOOL         SetupDiSetDeviceInstallParams(              HDEVINFO DeviceInfoSet, PSP_DEVINFO_DATA DeviceInfoData, PSP_DEVINSTALL_PARAMS DeviceInstallParams);
  BOOL         SetupDiSetDeviceInterfaceDefault(           HDEVINFO DeviceInfoSet, PSP_DEVICE_INTERFACE_DATA DeviceInterfaceData, DWORD Flags, PVOID Reserved);
  BOOL         SetupDiSetDeviceInterfacePropertyW(         HDEVINFO DeviceInfoSet, PSP_DEVICE_INTERFACE_DATA DeviceInterfaceData, WINAPI_DEVPROPKEY* PropertyKey, DEVPROPTYPE PropertyType, WINAPI_PBYTE PropertyBuffer, DWORD PropertyBufferSize, DWORD Flags);
  BOOL         SetupDiSetDevicePropertyW(                  HDEVINFO DeviceInfoSet, PSP_DEVINFO_DATA DeviceInfoData, WINAPI_DEVPROPKEY* PropertyKey, DEVPROPTYPE PropertyType, WINAPI_PBYTE PropertyBuffer, DWORD PropertyBufferSize, DWORD Flags);
  BOOL         SetupDiSetDeviceRegistryProperty(           HDEVINFO DeviceInfoSet, PSP_DEVINFO_DATA DeviceInfoData, WINAPI_SetupDeviceRegistryProperty Property, WINAPI_BYTE* PropertyBuffer, DWORD PropertyBufferSize);
  BOOL         SetupDiSetDriverInstallParams(              HDEVINFO DeviceInfoSet, PSP_DEVINFO_DATA DeviceInfoData, PSP_DRVINFO_DATA DriverInfoData, PSP_DRVINSTALL_PARAMS DriverInstallParams);
  BOOL         SetupDiSetSelectedDevice(                   HDEVINFO DeviceInfoSet, PSP_DEVINFO_DATA DeviceInfoData);
  BOOL         SetupDiSetSelectedDriver(                   HDEVINFO DeviceInfoSet, PSP_DEVINFO_DATA DeviceInfoData, PSP_DRVINFO_DATA DriverInfoData);
  BOOL         SetupDiUnremoveDevice(                      HDEVINFO DeviceInfoSet, PSP_DEVINFO_DATA DeviceInfoData);
  SP_LOG_TOKEN SetupGetThreadLogToken(                     );
  VOID         SetupSetThreadLogToken(                     SP_LOG_TOKEN LogToken);
  VOID         SetupWriteTextLog(                          SP_LOG_TOKEN LogToken, DWORD Category, DWORD Flags, PCTSTR MessageStr);
  VOID         SetupWriteTextLogError(                     SP_LOG_TOKEN LogToken, DWORD Category, DWORD LogFlags, DWORD Error, PCSTR MessageStr);
  VOID         SetupWriteTextLogInfLine(                   SP_LOG_TOKEN LogToken, DWORD Flags, HINF InfHandle, PINFCONTEXT Context);
  CONFIGRET    CM_Add_Empty_Log_Conf(                      PLOG_CONF plcLogConf, DEVINST dnDevInst, PRIORITY Priority, ULONG ulFlags);
  CONFIGRET    CM_Add_Empty_Log_Conf_Ex(                   PLOG_CONF plcLogConf, DEVINST dnDevInst, PRIORITY Priority, ULONG ulFlags, HMACHINE hMachine);
  CONFIGRET    CM_Add_ID(                                  DEVINST dnDevInst, PTSTR pszID, ULONG ulFlags);
  CONFIGRET    CM_Add_ID_Ex(                               DEVINST dnDevInst, PTSTR pszID, ULONG ulFlags, HMACHINE hMachine);
  CONFIGRET    CM_Add_Res_Des(                             PRES_DES prdResDes, LOG_CONF lcLogConf, RESOURCEID ResourceID, PCVOID ResourceData, ULONG ResourceLen, ULONG ulFlags);
  CONFIGRET    CM_Add_Res_Des_Ex(                          PRES_DES prdResDes, LOG_CONF lcLogConf, RESOURCEID ResourceID, PCVOID ResourceData, ULONG ResourceLen, ULONG ulFlags, HMACHINE hMachine);
  CONFIGRET    CM_Connect_Machine(                         PCTSTR UNCServerName, PHMACHINE phMachine);
  CONFIGRET    CM_Disconnect_Machine(                      HMACHINE hMachine);
  CONFIGRET    CM_Enumerate_Classes(                       ULONG ulClassIndex, LPGUID ClassGuid, ULONG ulFlags);
  CONFIGRET    CM_Enumerate_Classes_Ex(                    ULONG ulClassIndex, LPGUID ClassGuid, ULONG ulFlags, HMACHINE hMachine);
  CONFIGRET    CM_Enumerate_Enumerators(                   ULONG ulEnumIndex, PTCHAR Buffer, PULONG pulLength, ULONG ulFlags);
  CONFIGRET    CM_Enumerate_Enumerators_Ex(                ULONG ulEnumIndex, PTCHAR Buffer, PULONG pulLength, ULONG ulFlags, HMACHINE hMachine);
  CONFIGRET    CM_Free_Log_Conf(                           LOG_CONF lcLogConfToBeFreed, ULONG ulFlags);
  CONFIGRET    CM_Free_Log_Conf_Ex(                        LOG_CONF lcLogConfToBeFreed, ULONG ulFlags, HMACHINE hMachine);
  CONFIGRET    CM_Free_Log_Conf_Handle(                    LOG_CONF lcLogConf);
  CONFIGRET    CM_Free_Res_Des(                            PRES_DES prdResDes, RES_DES rdResDes, ULONG ulFlags);
  CONFIGRET    CM_Free_Res_Des_Ex(                         PRES_DES prdResDes, RES_DES rdResDes, ULONG ulFlags, HMACHINE hMachine);
  CONFIGRET    CM_Free_Res_Des_Handle(                     RES_DES rdResDes);
  CONFIGRET    CM_Free_Resource_Conflict_Handle(           CONFLICT_LIST clConflictList);
  CONFIGRET    CM_Get_Child(                               PDEVINST pdnDevInst, DEVINST dnDevInst, ULONG ulFlags);
  CONFIGRET    CM_Get_Child_Ex(                            PDEVINST pdnDevInst, DEVINST dnDevInst, ULONG ulFlags, HMACHINE hMachine);
  CONFIGRET    CM_Get_Class_Registry_Property(             LPGUID ClassGuid, ULONG ulProperty, PULONG pulRegDataType, PVOID Buffer, PULONG pulLength, ULONG ulFlags, HMACHINE hMachine);
  CONFIGRET    CM_Get_Depth(                               PULONG pulDepth, DEVINST dnDevInst, ULONG ulFlags);
  CONFIGRET    CM_Get_Depth_Ex(                            PULONG pulDepth, DEVINST dnDevInst, ULONG ulFlags, HMACHINE hMachine);
  CONFIGRET    CM_Get_Device_ID(                           DEVINST dnDevInst, PTCHAR Buffer, ULONG BufferLen, ULONG ulFlags);
  CONFIGRET    CM_Get_Device_ID_Ex(                        DEVINST dnDevInst, PTCHAR Buffer, ULONG BufferLen, ULONG ulFlags, HMACHINE hMachine);
  CONFIGRET    CM_Get_Device_ID_List(                      PCTSTR pszFilter, PTCHAR Buffer, ULONG BufferLen, ULONG ulFlags);
  CONFIGRET    CM_Get_Device_ID_List_Ex(                   PCTSTR pszFilter, PTCHAR Buffer, ULONG BufferLen, ULONG ulFlags, HMACHINE hMachine);
  CONFIGRET    CM_Get_Device_ID_List_Size(                 PULONG pulLen, PCTSTR pszFilter, ULONG ulFlags);
  CONFIGRET    CM_Get_Device_ID_List_Size_Ex(              PULONG pulLen, PCTSTR pszFilter, ULONG ulFlags, HMACHINE hMachine);
  CONFIGRET    CM_Get_Device_ID_Size(                      PULONG pulLen, DEVINST dnDevInst, ULONG ulFlags);
  CONFIGRET    CM_Get_Device_ID_Size_Ex(                   PULONG pulLen, DEVINST dnDevInst, ULONG ulFlags, HMACHINE hMachine);
  CONFIGRET    CM_Get_Device_Interface_List(               LPGUID InterfaceClassGuid, DEVINSTID pDeviceID, PTCHAR Buffer, ULONG BufferLen, ULONG ulFlags);
  CONFIGRET    CM_Get_Device_Interface_List_Size(          PULONG pulLen, LPGUID InterfaceClassGuid, DEVINSTID pDeviceID, ULONG ulFlags);
  CONFIGRET    CM_Get_DevNode_Status(                      PULONG pulStatus, WINAPI_CmProblemNumber* pulProblemNumber, DEVINST dnDevInst, ULONG ulFlags);
  CONFIGRET    CM_Get_DevNode_Status_Ex(                   PULONG pulStatus, WINAPI_CmProblemNumber* pulProblemNumber, DEVINST dnDevInst, ULONG ulFlags, HMACHINE hMachine);
  CONFIGRET    CM_Get_First_Log_Conf(                      PLOG_CONF plcLogConf, DEVINST dnDevInst, WINAPI_LogicalConfigFlags ulFlags);
  CONFIGRET    CM_Get_First_Log_Conf_Ex(                   PLOG_CONF plcLogConf, DEVINST dnDevInst, WINAPI_LogicalConfigFlags ulFlags, HMACHINE hMachine);
  CONFIGRET    CM_Get_HW_Prof_Flags(                       DEVINSTID pDeviceID, WINAPI_CsConfigFlags* pulValue, ULONG ulFlags);
  CONFIGRET    CM_Get_HW_Prof_Flags_Ex(                    DEVINSTID pDeviceID, ULONG ulHardwareProfile, WINAPI_CsConfigFlags* pulValue, ULONG ulFlags, HMACHINE hMachine);
  CONFIGRET    CM_Get_Log_Conf_Priority(                   LOG_CONF lcLogConf, PPRIORITY pPriority, ULONG ulFlags);
  CONFIGRET    CM_Get_Log_Conf_Priority_Ex(                LOG_CONF lcLogConf, PPRIORITY pPriority, ULONG ulFlags, HMACHINE hMachine);
  CONFIGRET    CM_Get_Next_Log_Conf(                       PLOG_CONF plcLogConf, LOG_CONF lcLogConf, ULONG ulFlags);
  CONFIGRET    CM_Get_Next_Log_Conf_Ex(                    PLOG_CONF plcLogConf, LOG_CONF lcLogConf, ULONG ulFlags, HMACHINE hMachine);
  CONFIGRET    CM_Get_Next_Res_Des(                        PRES_DES prdResDes, RES_DES rdResDes, RESOURCEID ForResource, PRESOURCEID pResourceID, ULONG ulFlags);
  CONFIGRET    CM_Get_Next_Res_Des_Ex(                     PRES_DES prdResDes, RES_DES rdResDes, RESOURCEID ForResource, PRESOURCEID pResourceID, ULONG ulFlags, HMACHINE hMachine);
  CONFIGRET    CM_Get_Parent(                              PDEVINST pdnDevInst, DEVINST dnDevInst, ULONG ulFlags);
  CONFIGRET    CM_Get_Parent_Ex(                           PDEVINST pdnDevInst, DEVINST dnDevInst, ULONG ulFlags, HMACHINE hMachine);
  CONFIGRET    CM_Get_Res_Des_Data(                        RES_DES rdResDes, PVOID Buffer, ULONG BufferLen, ULONG ulFlags);
  CONFIGRET    CM_Get_Res_Des_Data_Ex(                     RES_DES rdResDes, PVOID Buffer, ULONG BufferLen, ULONG ulFlags, HMACHINE hMachine);
  CONFIGRET    CM_Get_Res_Des_Data_Size(                   PULONG pulSize, RES_DES rdResDes, ULONG ulFlags);
  CONFIGRET    CM_Get_Res_Des_Data_Size_Ex(                PULONG pulSize, RES_DES rdResDes, ULONG ulFlags, HMACHINE hMachine);
  CONFIGRET    CM_Get_Resource_Conflict_Count(             CONFLICT_LIST clConflictList, PULONG pulCount);
  CONFIGRET    CM_Get_Resource_Conflict_Details(           CONFLICT_LIST clConflictList, ULONG ulIndex, PCONFLICT_DETAILS pConflictDetails);
  CONFIGRET    CM_Get_Sibling(                             PDEVINST pdnDevInst, DEVINST DevInst, ULONG ulFlags);
  CONFIGRET    CM_Get_Sibling_Ex(                          PDEVINST pdnDevInst, DEVINST DevInst, ULONG ulFlags, HMACHINE hMachine);
  CONFIGRET    CM_Get_Version(                             );
  CONFIGRET    CM_Get_Version_Ex(                          HMACHINE hMachine);
  CONFIGRET    CM_Is_Dock_Station_Present(                 PBOOL pbPresent);
  CONFIGRET    CM_Is_Dock_Station_Present_Ex(              PBOOL pbPresent, HMACHINE hMachine);
  CONFIGRET    CM_Is_Version_Available(                    WORD wVersion);
  CONFIGRET    CM_Is_Version_Available_Ex(                 WORD wVersion, HMACHINE hMachine);
  CONFIGRET    CM_Locate_DevNode(                          PDEVINST pdnDevInst, DEVINSTID pDeviceID, WINAPI_CM_Locate_DevNode_Flags ulFlags);
  CONFIGRET    CM_Locate_DevNode_Ex(                       PDEVINST pdnDevInst, DEVINSTID pDeviceID, WINAPI_CM_Locate_DevNode_Flags ulFlags, HMACHINE hMachine);
  CONFIGRET    CM_Modify_Res_Des(                          PRES_DES prdResDes, RES_DES rdResDes, RESOURCEID ResourceID, PCVOID ResourceData, ULONG ResourceLen, ULONG ulFlags);
  CONFIGRET    CM_Modify_Res_Des_Ex(                       PRES_DES prdResDes, RES_DES rdResDes, RESOURCEID ResourceID, PCVOID ResourceData, ULONG ResourceLen, ULONG ulFlags, HMACHINE hMachine);
  CONFIGRET    CM_Query_And_Remove_SubTree(                DEVINST dnAncestor, PPNP_VETO_TYPE pVetoType, LPTSTR pszVetoName, ULONG ulNameLength, ULONG ulFlags);
  CONFIGRET    CM_Query_And_Remove_SubTree_Ex(             DEVINST dnAncestor, PPNP_VETO_TYPE pVetoType, LPTSTR pszVetoName, ULONG ulNameLength, ULONG ulFlags);
  CONFIGRET    CM_Query_Resource_Conflict_List(            PCONFLICT_LIST pclConflictList, DEVINST dnDevInst, RESOURCEID ResourceID, PCVOID ResourceData, ULONG ResourceLen, ULONG ulFlags, HMACHINE hMachine);
  CONFIGRET    CM_Reenumerate_DevNode(                     DEVINST dnDevInst, ULONG ulFlags);
  CONFIGRET    CM_Reenumerate_DevNode_Ex(                  DEVINST dnDevInst, ULONG ulFlags, HMACHINE hMachine);
  CONFIGRET    CM_Request_Device_Eject(                    DEVINST dnDevInst, PPNP_VETO_TYPE pVetoType, LPTSTR pszVetoName, ULONG ulNameLength, ULONG ulFlags);
  CONFIGRET    CM_Request_Device_Eject_Ex(                 DEVINST dnDevInst, PPNP_VETO_TYPE pVetoType, LPTSTR pszVetoName, ULONG ulNameLength, ULONG ulFlags);
  CONFIGRET    CM_Request_Eject_PC(                        );
  CONFIGRET    CM_Request_Eject_PC_Ex(                     HMACHINE hMachine);
  CONFIGRET    CM_Set_Class_Registry_Property(             LPGUID ClassGuid, ULONG ulProperty, PCVOID Buffer, ULONG ulLength, ULONG ulFlags, HMACHINE hMachine);
  CONFIGRET    CM_Set_DevNode_Problem(                     DEVINST dnDevInst, WINAPI_CmProblemNumber ulProblem, ULONG ulFlags);
  CONFIGRET    CM_Set_DevNode_Problem_Ex(                  DEVINST dnDevInst, WINAPI_CmProblemNumber ulProblem, ULONG ulFlags, HMACHINE hMachine);
  CONFIGRET    CM_Setup_DevNode(                           DEVINST dnDevInst, ULONG ulFlags);
  DWORD        CMP_WaitNoPendingInstallEvents(             DWORD dwTimeout);
]]
return ffi.load( 'Setupapi.dll' )
