require( 'ffi/winapi/headers/windows' )
require( 'ffi/winapi/headers/shell' )
local ffi = require( 'ffi' )
ffi.cdef [[
  typedef void* IConnectableCredentialProviderCredential; //Interface
  typedef void* ICredentialProvider; //Interface
  typedef void* ICredentialProviderCredential; //Interface
  typedef void* ICredentialProviderCredentialEvents; //Interface
  typedef void* ICredentialProviderEvents; //Interface
  typedef void* ICredentialProviderFilter; //Interface
  typedef void* IQueryContinueWithStatus; //Interface
  typedef UINT CREDENTIAL_PROVIDER_FIELD_STATE; //Alias
  static const CREDENTIAL_PROVIDER_FIELD_STATE CPFS_HIDDEN = 0;
  static const CREDENTIAL_PROVIDER_FIELD_STATE CPFS_DISPLAY_IN_SELECTED_TILE = 1;
  static const CREDENTIAL_PROVIDER_FIELD_STATE CPFS_DISPLAY_IN_DESELECTED_TILE = 2;
  static const CREDENTIAL_PROVIDER_FIELD_STATE CPFS_DISPLAY_IN_BOTH = 3;
  typedef UINT CREDENTIAL_PROVIDER_GET_SERIALIZATION_RESPONSE; //Alias
  static const CREDENTIAL_PROVIDER_GET_SERIALIZATION_RESPONSE CPGSR_NO_CREDENTIAL_NOT_FINISHED = 0;
  static const CREDENTIAL_PROVIDER_GET_SERIALIZATION_RESPONSE CPGSR_NO_CREDENTIAL_FINISHED = 1;
  static const CREDENTIAL_PROVIDER_GET_SERIALIZATION_RESPONSE CPGSR_RETURN_CREDENTIAL_FINISHED = 2;
  typedef UINT CREDENTIAL_PROVIDER_STATUS_ICON; //Alias
  static const CREDENTIAL_PROVIDER_STATUS_ICON CPSI_NONE = 0;
  static const CREDENTIAL_PROVIDER_STATUS_ICON CPSI_ERROR = 1;
  static const CREDENTIAL_PROVIDER_STATUS_ICON CPSI_WARNING = 2;
  static const CREDENTIAL_PROVIDER_STATUS_ICON CPSI_SUCCESS = 3;
  typedef UINT CREDENTIAL_PROVIDER_USAGE_SCENARIO; //Alias
  static const CREDENTIAL_PROVIDER_USAGE_SCENARIO CPUS_INVALID = 0;
  static const CREDENTIAL_PROVIDER_USAGE_SCENARIO CPUS_LOGON = 1;
  static const CREDENTIAL_PROVIDER_USAGE_SCENARIO CPUS_UNLOCK_WORKSTATION = 2;
  static const CREDENTIAL_PROVIDER_USAGE_SCENARIO CPUS_CHANGE_PASSWORD = 3;
  static const CREDENTIAL_PROVIDER_USAGE_SCENARIO CPUS_CREDUI = 4;
  static const CREDENTIAL_PROVIDER_USAGE_SCENARIO CPUS_PLAP = 5;
  typedef UINT CREDENTIAL_PROVIDER_FIELD_INTERACTIVE_STATE; //Alias
  static const CREDENTIAL_PROVIDER_FIELD_INTERACTIVE_STATE CPFIS_NONE = 0;
  static const CREDENTIAL_PROVIDER_FIELD_INTERACTIVE_STATE CPFIS_READONLY = 1;
  static const CREDENTIAL_PROVIDER_FIELD_INTERACTIVE_STATE CPFIS_DISABLED = 2;
  static const CREDENTIAL_PROVIDER_FIELD_INTERACTIVE_STATE CPFIS_FOCUSED = 3;
  typedef struct CREDENTIAL_PROVIDER_CREDENTIAL_SERIALIZATION {
    ULONG ulAuthenticationPackage;
    GUID clsidCredentialProvider;
    ULONG cbSerialization;
    byte* rgbSerialization;
  } CREDENTIAL_PROVIDER_CREDENTIAL_SERIALIZATION;
  typedef UINT CREDENTIAL_PROVIDER_FIELD_TYPE; //Alias
  static const CREDENTIAL_PROVIDER_FIELD_TYPE CPFT_INVALID = 0;
  static const CREDENTIAL_PROVIDER_FIELD_TYPE CPFT_LARGE_TEXT = 1;
  static const CREDENTIAL_PROVIDER_FIELD_TYPE CPFT_SMALL_TEXT = 2;
  static const CREDENTIAL_PROVIDER_FIELD_TYPE CPFT_COMMAND_LINK = 3;
  static const CREDENTIAL_PROVIDER_FIELD_TYPE CPFT_EDIT_TEXT = 4;
  static const CREDENTIAL_PROVIDER_FIELD_TYPE CPFT_PASSWORD_TEXT = 5;
  static const CREDENTIAL_PROVIDER_FIELD_TYPE CPFT_TILE_IMAGE = 6;
  static const CREDENTIAL_PROVIDER_FIELD_TYPE CPFT_CHECKBOX = 7;
  static const CREDENTIAL_PROVIDER_FIELD_TYPE CPFT_COMBOBOX = 8;
  static const CREDENTIAL_PROVIDER_FIELD_TYPE CPFT_SUBMIT_BUTTON = 9;
  typedef struct CREDENTIAL_PROVIDER_FIELD_DESCRIPTOR {
    DWORD dwFieldID;
    CREDENTIAL_PROVIDER_FIELD_TYPE cpft;
    LPWSTR pszLabel;
    GUID guidFieldType;
  } CREDENTIAL_PROVIDER_FIELD_DESCRIPTOR;
]]
